### PR TITLE
Add Number.clamp.

### PR DESCRIPTION
**Pull request by technorama**

### CODE REVIEW

**Comment by asterite** [comment]
Looks good, but I'm not sure about the method accepting a Range, because it could be exclusive and I don't know what that would mean in that case.

**Comment by bcardiff** [comment]
I agree with @asterite . Range it's not just a lower/upper bound tuple.
Also, I think usually you will have the limits constants or one of them from a variable. So the non-range alternative seems good enough.

I hadn't heard the term clamp before. Is it well known enough? clip/limit sounds clearer to me.

**Comment by asterite** [comment]
"clamp" is pretty known, at least I know the term from video game programming

**Comment by technorama** [comment]
Updated to raise if given an exclusive range.

The Range method is for convenience.  The range may be created by another class or library.  You want a number clamped within the range.  `1.clamp(range.begin, range.end)` looks bad.

**Comment by jhass** [comment]
Mmh, we could support the exclusive range if we do #1391, or already using `pred` from #1215

**Comment by technorama** [comment]
In ruby they debated the naming for over 3 years.  I don't think it's been merged yet.  

Clamp is in C#, OpenGL, and every video game framework I've seen.

**Comment by Nakilon** [comment]
What about `.clamp(a, b)`, where a > b?

**Comment by technorama** [comment]
>  min > max

The method was used incorrectly.  Similar issues exist in `Range.includes?`.   If you want I'll `raise PEBCAK.new`.

**Comment by jhass** [comment]
`PEBCAK` exists and is called `ArgumentError` ;)

**Comment by jhass** [comment]
Let's try this for a while, we can still always drop, expand or rename it if we feel it doesn't work out in practice.

**Pull request merged**
