### PR TITLE
Add .DS_Store to .gitignore

### PR DESCRIPTION
**Pull request by Xyz10**
.DS_Store is a common file created to store folder attributes in Finder (default file browser on OS X).

### CODE REVIEW

**Comment by asterite** [comment]
I have this in my [~/.gitignore_global](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore). That nobody suggested this before makes me think most people have this on their global gitignore, but I don't know. Otherwise you end up having this file in basically every `.gitignore` out there.

**Comment by Xyz10** [comment]
I usually do as well (I appear to have forgotten to add it on this machine when I got it). But not everybody takes the time to do so, and some occasionally forget (I'm a perfect example of this one! :P).

I won't take it personally if you'd prefer not to have this - just thought I'd submit in case you did (noticed it as I was writing up a git dependency module).

**Comment by asterite** [comment]
I personally don't mind adding it, but I'd like to know what others think :-)

**Comment by yyyc514** [comment]
Lets just add.  It's not hard to have a small section of junk ignore files like this - and it's difficult to maintain over time or anything.

**Pull request merged**
