### PR TITLE
Fix #1302: File#tell: SEEK_CUR is a local constant

### LINKED ISSUE #1302: File#tell doesn't work
```
in crystal/src/io/file_descriptor_io.cr:52: undefined constant LibC::SEEK_CUR
```

### PR DESCRIPTION
**Pull request by lbguilherme**
This fixes issue #1302.

### CODE REVIEW

**Comment by BlaXpirit** [comment]
:open_mouth: you're fast!

**Comment by jhass** [comment]
Makes you wonder if we can have a spec for this though.

**Comment by lbguilherme** [comment]
I was thinking about doing one, but I'm not sure how to do a spec that involves dealing with a file. Create a temp file, operate on it and then delete it?

**Comment by jhass** [comment]
I think we already do that a couple of times, yeah.

**Comment by asterite** [comment]
Oh, this would be really nice. Note that this class is buffered and right now the result of tell is broken IIRC. You can always compre against Ruby to check the correct behavior :)

**Comment by lbguilherme** [comment]
I have updated with some specs and fixes for `seek` and `tell` on buffered io. This also fixes #1306.

**Comment by jhass** [comment]
:+1:

**Comment by lbguilherme** [comment]
Is this normal?

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> The build has been terminated

**Comment by jhass** [comment]
Most likely not your issue at least, the 32bit build seems to stall sometimes, maybe a sleep call going wrong or idk.

**Comment by asterite** [comment]
Awesome, thanks!!

**Comment by asterite** [comment]
Forgot to link this: https://github.com/manastech/crystal/commit/6cf0ebc88625132981b441695593058a2f4e4954

I'm wondering, would it make sense to move `tell` and `seek` to `File`? For pipes and sockets these will always fail...

**Comment by lbguilherme** [comment]
@asterite All the spec for it is located at `file_spec.cr` because it indeed makes no sense anywhere else. I would agree with this move.

As a side note, `StringIO` should support seek and tell as well, so maybe the `Seek` enum should still remain on `IO`, where each specialization is free to implement `seek`/`tell` as it pleases.

**Pull request merged**
