### PR TITLE
Please respect user's CRYSTAL_PATH

### PR DESCRIPTION
**Pull request by MakeNowJust**

### CODE REVIEW

**Comment by jhass** [comment]
I can get behind ignoring empty elements, but I'm not sure about the change in `bin/crystal`, it may (or even is already?) be used to include the stdlib of another Crystal version, and in those scenarios would lead to subtle but still wrong behaviour. What do you think about ordering the local stdlib before it?

**Comment by MakeNowJust** [comment]
@jhass Sorry about "No description provided." pull request.
I uncommented `def !~` in #1904. I examined the reason why we forget to uncomment it.  I understood it as the current version compiler cannot parses the new syntax. To solve this problem, we need to separate stdlib between to compile "new compiler" and to compile others. So, I want to inject `CRYSTAL_PATH` from the outside. If this PR merged, I want to fix `.travis.yml` to a like https://gist.github.com/MakeNowJust/707e5fd13861fb7274e6/revisions#diff-354f30a63fb0907d4ad57269548329e3R15.

**Comment by jhass** [comment]
I'm not sure I understand you tbh, but I don't think I would accept the change to `.travis.yml`. And no, we don't want to compile a new compiler with the old stdlib on Travis, we want to ensure the old compiler can compile the next stdlib, otherwise version n+1 can't be compiled with version n.

**Comment by MakeNowJust** [comment]
Thanks for merging #1917.

**Pull request closed without merging**
