### PR TITLE
add support for polymorphic macro methods

### LINKED ISSUE #1590: macro methods don't support polymorphism
``` crystal
require "json"

module DDP
  abstract class Message
    def initialize(@type)
    end

    macro def self.parse(json) : Message
      hash = JSON.parse(json)
      raise "malformed json: #{json}" unless hash.is_a?(Hash)
      type = hash["msg"]?
      raise "malformed message: #{json}" unless type
      case(type)
      {% for subclass in @type.subclasses %}
      when {{subclass.name.split("::").last.underscore}}
        {{subclass}}.from_json(json)
      {% end %}
      else raise "unknown message type: #{type}"
      end
    end

    def on_response
    end
  end

  class Connect < Message
    json_mapping({
      type: { key: "msg", type: String },
    }, true)
  end
end
```

raises `Error in ./src/ddp/message.cr:8: expected 'parse' to return DDP::Message, not DDP::Connect`

### PR DESCRIPTION
**Pull request by jreinert**
fixes #1590

### CODE REVIEW

**Comment by bcardiff** [comment]
@jreinert would you add some specs please?

It's great to have more people willing to work on `src/compiler/crystal/**` :-)

**Comment by jreinert** [comment]
@bcardiff i'll give it a try and will update the PR

**Comment by jreinert** [comment]
@asterite @waj anything else you need for this? I'm kinda dependent on this for working on improvements for WebSocket. It allows the creation of dispatcher methods for instances of sub classes of an abstract parent class.
as in:

``` crystal
abstract class Foo
  macro def self.build(some, attributes) : Foo
    case(attributes)
    {% for subclass in @type.subclasses %}
      when {{subclass.name.underscore}} then {{subclass}}.new(some, attributes)
    {% end %}
      else raise "unknown foo"
    end
  end
end

class Bar
end
```

**Comment by asterite** [comment]
@jreinert Hey, thanks! It's really awesome that you dared cross the `src/compiler/crystal/` barrier. And the best thing is, I think you got it right! At first I though this didn't work because the compiler works more or less like this:

1. Sees call `foo.bar`
2. Sees that method `bar` is a  macro def, so doesn't type it's body and assigns its type to the return type
3. Once the type inference phase finishes, type the body and check that it matches the type indicated by the return type

Now, if you say the method returns `Foo` and then you return `Bar` and check that it's covariant, that would be a lie to the compiler. OK, Bar is covariant, but the expression that depended on the type being `Foo` now gets a `Bar`, and that's not the same as `Foo`. It would be the same if it were `Foo+`, which means "Foo or any of its subclasses" (we make that distinction, I'm still not sure it's a good thing). So things wouldn't work properly.

However, when we type the body, we are actually binding the result to the generated def, so that gets propagated everywhere and everything works. So your change is correct :-)

Let me check it a bit more, but I think it's OK. I'll probably do this on Monday.

**Comment by asterite** [comment]
@jreinert I'll merge this, but could you first make some changes to the specs? For checking errors we use `assert_error`. For example [here](https://github.com/manastech/crystal/blob/master/spec/compiler/type_inference/alias_spec.cr#L71-L77) (line numbers are usually OK because we test them in the parser specs). Then, if you want to codegen something but don't care about the result, invoke `codegen` instead of `run`. But your specs seem to care about correct typing, so these should go into [this file](https://github.com/manastech/crystal/blob/master/spec/compiler/type_inference/macro_spec.cr) and check that some expression has the type you expect. Some codegen specs would be nice too, but in this case I'd do something like:

```crystal
class Foo
  def foo
    1
  end
end

class Bar < Foo
  def foo
    2
  end
end

class Target
  macro def target : Foo
    Bar.new
  end
end

Target.new.target.foo
```

and check that `run(...).to_i.should eq(2)`, so we check that the program behaves well.

**Comment by asterite** [comment]
@jreinert I'll merge this, but could you first make some changes to the specs? For checking errors we use `assert_error`. For example [here](https://github.com/manastech/crystal/blob/master/spec/compiler/type_inference/alias_spec.cr#L71-L77) (line numbers are usually OK because we test them in the parser specs). Then, if you want to codegen something but don't care about the result, invoke `codegen` instead of `run`. But your specs seem to care about correct typing, so these should go into [this file](https://github.com/manastech/crystal/blob/master/spec/compiler/type_inference/macro_spec.cr) and check that some expression has the type you expect. Some codegen specs would be nice too, but in this case I'd do something like:

```crystal
class Foo
  def foo
    1
  end
end

class Bar < Foo
  def foo
    2
  end
end

class Target
  macro def target : Foo
    Bar.new
  end
end

Target.new.target.foo
```

and check that `run(...).to_i.should eq(2)`, so we check that the program behaves well.

**Comment by jreinert** [comment]
@asterite thanks for the hints. I didn't yet stumble across `spec/compiler/type_inference/macro_spec.cr`. I updated the specs.

**Comment by asterite** [comment]
Awesome, thanks!

**Pull request merged**
