### PR TITLE
Time Format: %W for week number of year

### PR DESCRIPTION
**Pull request by phortx**

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! Could I ask you some specs? Then you'll know that it works, and also Travis will tell us that it works. And then if we want to optimize the methods we can rely on the specs.

**Comment by asterite** [comment]
Also, I don't know why you use intermediate format calls, like this:

```crystal
day_of_year = TimeFormat.new("%j").format(date).to_i
```

Instead of:

```crystal
day_of_year = date.day_of_year
```

**Comment by phortx** [comment]
> Could I ask you some specs?

Done.


> Also, I don't know why you use intermediate format calls, like this:

Since, Time doesn't have those methods, I didn't found any other way. Could you give my any advice?


There was another stupid naming issue, I've fixed that. Was late yesterday ;)

**Comment by asterite** [comment]
Hi,

There's `Time#day_of_week`, which gives you an Enum. Then you call `value` to convert it to 0..6.

I tried your specs with Ruby:

```ruby
Time.new(2015, 5, 22).strftime("%W") #=> 20 (21 in your specs)
Time.new(2015, 3, 24).strftime("%W") #=> 12 (13 in your specs)
Time.new(1989, 10, 26).strftime("%W") #=> 43 (like in your specs)
Time.new(2012, 4, 15).strftime("%W") #=> 15 (16 in your specs)
```

In Ruby there's also %V, which gives you the week-number according to ISO-8601, so I thought maybe your implementation did that, but:

```ruby
Time.new(2015, 5, 22).strftime("%V") #=> 21 (like in your specs)
Time.new(2015, 3, 24).strftime("%V") #=> 13 (like in your specs)
Time.new(1989, 10, 26).strftime("%V") #=> 43 (like in your specs)
Time.new(2012, 4, 15).strftime("%V") #=> 15 (16 in your specs)
```

So apparently it's neither. I'm not sure where's the problem.

**Comment by phortx** [comment]
Hi @asterite,

thank you very much for your feedback!

In fact you're right, compared to ruby, my implementation is equivalent to `%V`. I'll update the Pull Request in order to provide both `%W` beginning with 0 and `%V` beginning with 1.

The algorithm is from a stackoverflow answer for week number calculation, in fact it works for the first examples, the last one is wrong, your right. Seems like the algorithm is buggy, I'll search for a better one an update the PR.

Also you'll see a commit which introduces the usage of `Time#day_of_week` and `Time#day_of_week` methods.

**Comment by jhass** [comment]
Btw, if you want to get to a clean commit history, `git rebase -i` makes it easy:

```
git remote add upstream git://github.com/manastech/crystal.git
git fetch upstream
git checkout feature/time-format-week-of-year
git rebase -i upstream/master
# you can reorder the commits, drop them and combine them by editing pick to squash or fix
git push -f origin feature/time-format-week-of-year # Assuming you cloned from your fork
```

You can also edit a commit with `git commit --amend`.

**Comment by phortx** [comment]
@jhass Yes, I'll do a squash after finishing the QA with @asterite. Thanks :)

**Comment by phortx** [comment]
It's acutally pretty hard to find a working algorithm ... I tried several implementions I found on the web, non of them worked in all edge cases ...

**Comment by asterite** [comment]
The best way to get the same behavior as Ruby is to check Ruby's source code ;-)

**Comment by phortx** [comment]
> The best way to get the same behavior as Ruby is to check Ruby's source code ;-)

Obviously ;) I did that as one of my first steps, Ruby just uses `time.h`. I could use `time.h`s `strftime` too for this particular use case, but that feels really stupid, since everything in TimeFormat is "hand coded" but that particular functinality uses strftime, which could be uses for everything else too. IMHO this is a all or nothing refactoring, isn't it? What do you think?

Unfortunately I'm not deep enough in C, time.h, crystal (yet) and the TimeFormatter and there are no specs for the TimeFormatter. So I wouldn't feel comfortable with doing such a big refactoring.

**Comment by asterite** [comment]
@phortx Ruby doesn't use `time.h`. Here's the [week number](https://github.com/ruby/ruby/blob/trunk/strftime.c#L1000-L1016) algorithm. There's also the [ISO week number](https://github.com/ruby/ruby/blob/trunk/strftime.c#L879-L984) algorithm.

I don't have time now to port these to Crystal, but you can try to do it. Specs will help ;-)

I would add `week_number` and `iso_week_number` methods to Time, and make TimeFormat use them.

**Comment by phortx** [comment]
@asterite Oh! Thank you ... I thought `strftime` is `strftime` of `time.h` ... Sorry, my fault. I'll try it this weekend.

**Comment by jhass** [comment]
Hey @phortx still interested in getting this in?

**Comment by phortx** [comment]
Yes, but I couldn't implement it due lack of time :(

If you need it and want to do it, feel free to continue my work.

**Comment by asterite** [comment]
I'm going to close this. Please send a different pull request implementing %W and/or %V correctly with specs. Thanks!

**Pull request closed without merging**
