### PR TITLE
add type_vars method for type nodes in macros

### PR DESCRIPTION
**Pull request by jreinert**

### CODE REVIEW

**Comment by asterite** [comment]
It's [here](https://github.com/manastech/crystal/blob/master/docs/macros.cr#L1126-L1129), although I do agree that `type_vars` is a better name.

**Comment by jreinert** [comment]
hmm then maybe `type_params` is broken? I tried using it in the spec instead of `type_vars` and got an empty array

**Comment by asterite** [comment]
Oh, the difference is that you want the names (for example the `T` in `Array(T)`) while the current `type_params` gives you the types of instantiated generic types. Do you want to merge the two of them into a single `type_vars` macro method?

**Comment by jreinert** [comment]
@asterite: I've merged the methods into type_vars. Anything else you need?

**Comment by asterite** [comment]
Looks good now, thanks!

**Comment by jreinert** [comment]
@asterite sorry, should've squashed. I'll remember next time

**Pull request merged**
