### PR TITLE
adding the sieve of eratosthenes example.

### PR DESCRIPTION
**Pull request by mrjbq7**
I thought it might be nice to preserve the example in the ``samples`` directory.

### CODE REVIEW

**Comment by asterite** [comment]
Definitely. Thanks!

**Comment by mrjbq7** [comment]
FYI, this is a faster sieve that uses a 210 wheel to reduce the number of candidates that need to be checked.  It should run in about 6 seconds on my computer in C but runs in about 27 seconds in Crystal.  Probably some low hanging fruit like using a BitArray (if available?) and other low-level improvements.

```crystal
# Compute prime numbers up to 1_000_000_000 with the Sieve of Eratosthenes
max = 1_000_000_000

wheel = [2,4,2,4,6,2,6,4,2,4,6,6,2,6,4,2,6,4,6,8,4,2,4,2,4,
         8,6,4,6,2,4,6,2,6,6,4,2,4,6,2,6,4,2,4,2,10,2,10]

bits = ((((max / 210) + 1) * 210) / 2) + 6
sieve = Array.new(bits, true)
sieve[0] = false
sieve[4] = false

upto = Math.sqrt(max)

i = 11
while i < upto
  wheel.each do |j|
    if sieve[i/2]
      (i * i).step(max, i * 2) do |j|
        sieve[j/2] = false
      end
    end
    i += j
  end
end

primes = [2,3,5,7]
i = 11
while i <= max
  wheel.each do |j|
    if sieve[i/2]
      primes.push(i)
    end
    i += j
    if i > max
       break
    end
  end
end

puts primes.length
```

**Comment by asterite** [comment]
@mrjbq7 Did you compile with `--release`? Make sure to read [this](http://crystal-lang.org/docs/using_the_compiler/index.html).

On my machine it takes 6.2 seconds.

**Comment by asterite** [comment]
And it takes about 22.25 seconds without the `--release` flag, so... ;-)

**Comment by mrjbq7** [comment]
@asterite aha! nice!

Would you be interested if I contributed a BitArray implementation and this example for use as a benchmark?

**Comment by mrjbq7** [comment]
(Actually, I tried using a simple bit array below and it slows down the sieve a little bit, perhaps I need to learn a bit more about how to express low-level math concepts used).

```crystal
# Compute prime numbers up to 100_000_000 with the Sieve of Eratosthenes
max = 1_000_000_000

wheel = [2,4,2,4,6,2,6,4,2,4,6,6,2,6,4,2,6,4,6,8,4,2,4,2,4,
         8,6,4,6,2,4,6,2,6,6,4,2,4,6,2,6,4,2,4,2,10,2,10]

bits = ((((max / 210) + 1) * 210) / 2) + 6

ints = (bits + 31) >> 5
sieve = Array.new(ints, 0xffffffff)
sieve[0 >> 5] &= ~(1 << (0 & 31))
sieve[4 >> 5] &= ~(1 << (4 & 31))

upto = Math.sqrt(max).to_i

i = 11
while i < upto
  wheel.each do |j|
    if sieve[(i/2) >> 5] & (1 << ((i/2) & 31)) > 0
      (i * i).step(max, i * 2) do |j|
        sieve[(j/2) >> 5] &= ~(1 << ((j/2) & 31))
      end
    end
    i += j
  end
end

primes = [2,3,5,7]
i = 11
while i <= max
  wheel.each do |j|
    if sieve[(i/2) >> 5] & (1 << ((i/2) & 31)) > 0
      primes.push(i)
    end
    i += j
    if i > max
       break
    end
  end
end

puts primes.length
```

**Comment by asterite** [comment]
@mrjbq7 Note that we already have a [BitArray](https://github.com/manastech/crystal/blob/master/src/bit_array.cr). I [just added](https://github.com/manastech/crystal/commit/55f9634bb6856c6f77ce658691d979b9b4a3f3ad) a way to initialize it to all `true` by default because that was missing. Here's your original code but using a BitArray (just two lines differ):

```crystal
# Compute prime numbers up to 1_000_000_000 with the Sieve of Eratosthenes
require "bit_array" # this line is added

max = 1_000_000_000

wheel = [2,4,2,4,6,2,6,4,2,4,6,6,2,6,4,2,6,4,6,8,4,2,4,2,4,
         8,6,4,6,2,4,6,2,6,6,4,2,4,6,2,6,4,2,4,2,10,2,10]

bits = ((((max / 210) + 1) * 210) / 2) + 6
sieve = BitArray.new(bits, true) # this is the changed line
sieve[0] = false
sieve[4] = false

upto = Math.sqrt(max)

i = 11
while i < upto
  wheel.each do |j|
    if sieve[i/2]
      (i * i).step(max, i * 2) do |j|
        sieve[j/2] = false
      end
    end
    i += j
  end
end

primes = [2,3,5,7]
i = 11
while i <= max
  wheel.each do |j|
    if sieve[i/2]
      primes.push(i)
    end
    i += j
    if i > max
       break
    end
  end
end

puts primes.length
```

It takes the same time for me... maybe BitArray isn't implemented in an efficient way?

But the memory usage is cut down to half, so that's definitely a win.

**Pull request merged**
