### PR TITLE
Make parentheses mandatory for def and macro arguments

### PR DESCRIPTION
**Pull request by asterite**
As the title says, this makes parentheses mandatory for def and macro arguments. That means that this:

```crystal
def foo x, y
end
```

will give a parse error.

There are many reasons for this breaking change, but this one is the main one:

```crystal
def foo arg : String
end
```

Is the above a def with one argument restricted to a String, or a def with one argument without restrictions that returns a String?

This ambiguity is solved by using parentheses:

```crystal
def foo(arg : String)
end

def foo(arg) : String
end
```

Other reasons:
1. There's always an ongoing discussion between liking/disliking parentheses in method arguments. Mixing these two styles is ugly in a single code base. For example in the standard library and compiler we always use parentheses, but sometimes we have to accept pull requests without parens and it's annoying to just ask to change that.
2. Parentheses aren't annoying and don't hinder readability in defs. In calls it's more understandable because it reads like an action or sentence, "do this", "write that", but for a method definition it doesn't make much sense.
3. Me, @waj, and many at Manas generally dislike methods written that way :-P

The plan is to merge this starting from the next release. The current release will introduce the formatter, which, in addition to reformat code, will also add parentheses to defs and macros. This will allow you to run `crystal tool format` on your project to update it to the latest version of the language. Then we'll merge this.

This PR is mainly to let you know about this breaking change (and, of course, hacktober ;-))

### CODE REVIEW

**Comment by kirbyfan64** [comment]
I don't mind this at all. As long as I can still call them without parens, +1!

**Comment by benoist** [comment]
I'm also a really against function defs without parentheses.  So +1 from me as well

Also it's pretty awesome that the formatter will do most of the work in that part!

**Comment by sdogruyol** [comment]
:+1:  for parans in defs

**Comment by asterite** [comment]
Another reason is that this is the recommended way according to the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide#method-parens) :-)

**Comment by ysbaddaden** [comment]
:+1: as long as I still can `def foo; end` of course!

**Comment by jhass** [comment]
I see I'm on a sinking ship here :( I like omitting them, it's easier to type for me. I never had the ambiguity issue, `:` simply has a high precedence and binds to the parameter if present. If you want to specify the return type add parens to disambiguate, just like everywhere else where precedence is involved. All my Crystal projects omit them (and sorry, I won't just run the formatter over it, my style is too opinionated for such a tool to work at all). In the Ruby world the reasoning always is something about hard to tell apart the method name from the arguments, which to me was never a problem since my editor uses different colors there. I have no problem with following the styleguides in other codebases, but would've been nice to keep the freedom (and consistency with calls) for my own projects.

**Comment by ozra** [comment]
Strong +1.

**Comment by asterite** [comment]
@jhass The main issue is that if somebody writes:

```crystal
def foo arg : String
end
```

and we allow omitting the parentheses, the above is still valid code but it's confusing (to see the return type you usually see past the last `:` in the line, after any parens, if any, but now that rule doesn't apply anymore). Forcing a parentheses there is just one step away from forcing it in any case.

Another reason is that coloring might not always be available in an editor (for example a raw vi).

And another reason is that there always seems to be a discussion over this, but not over calls. In calls you are usually free to do whatever you feel like, and everyone think it's OK. So this change will make those discussions vanish, in the same way that the formatter will almost impose a style on your code. You loose a bit of freedom, but everyone benefits from consistency. 

And I do hope you run the formatter on your code! Otherwise it will stop compiling.

**Comment by jhass** [comment]
Well, not that it matters anything, but I've had the same discussion over calls too.

**Comment by asterite** [comment]
And what's your opinion on calls? Always without parens? Always with parens?

**Comment by jhass** [comment]
I usually leave them off for the outermost call, except when there's a modifier-if following, though even there not strictly so.

**Comment by asterite** [comment]
Calls can be nested, so in `foo 1, bar 2, 3` you need parentheses to disambiguate between `foo 1, bar(2), 3` and `foo 1, bar(2, 3)` , but def arguments can't be nested so there's no need to disambiguate anything.

But note that the formatter will preserve parentheses or spaces in calls, it won't add parentheses in that case.

**Comment by jhass** [comment]
This is just one example though, I expect there to be other instances where it will apply a dogma. And where possible exactly means where there's not semantic ambiguity.

**Comment by ozra** [comment]
So there won't be any configurations of the formatter?

**Comment by will** [comment]
Found the branch before the issue. I'm in strongly favor of enforcing parens on method declarations, but only due to aesthetic feelings.

**Comment by technorama** [comment]
+1 for consistency.  Either make them mandatory when defining **and** calling or change the style on both to drop them except when required.  I'm for moving back to `::` for return types.  I realize the `:` change was for consistency but now we have an even bigger inconsistency with parenthesis.  Why is defining different than calling?  (I'm not asking a parser question but a language design question)  Why the difference?  Just cuz?

Look at the parenthesis issue as an outsider or as a teacher trying to explain why this is pretty much the same thing but with a different syntax.  Which of the following is easier for new comers to comprehend?

With mandatory parenthesis:
* Parenthesis are mandatory in declaration.
* Parenthesis are optional when calling.
* Parenthesis are mandatory when disambiguating method parameters.

Without parenthesis:
* Parenthesis aren't used except when disambiguating method parameters.

**Comment by ozra** [comment]
Personally I like consistency for declaration - it's more formal. So parentheses for _formal parameters_, but voluntary at _call arguments_, since expression code is good to be able to write.. eh, more expressive.
I always avoid parens in code except when needed for disabiguation, and then sometimes I use "lisp style" grouping parens instead of "arg-parens".
When declaring, I _always_ use parens - even for empty parameter list.
Just my view of what looks clear.

**Pull request merged**
