### PR TITLE
Align consecutive assignments if they are logically grouped

### LINKED ISSUE #1757: Formatter: questions about alignment of assignations
Hello,

This is the 3rd report I submit about the formatter and forgot to say something: thank you for the formatter! :heart: :heart: :heart:

Really appreciate the work put towards it and definitely will iron some details aiming to provide a unified usage of the language.

This is a question about alignment of assignations. Right now constant definitions get aligned:

From:

```crystal
module X
  A = 1
  ABC = 10
end
```

To:

```crystal
module X
  A   =  1
  ABC = 10
end
```

Which is great.

However, this seems only to apply to constants.

From my time dealing with Ruby and several projects and coding styles, I found quite useful align LHS (shorter or larger) to the equal sign:

```crystal
a   = 1
abc = 10
```

Will that be possible? (actually, will that be desired?)

Thank you :heart: :heart: :heart:

### PR DESCRIPTION
**Pull request by asterite**
This fixes #1757.

One idea that came to my mind, because I'd really like to have assignments aligned (it looks nice and it's a bit more readable) is to align consecutive assignments if they are in a separate "logical block". A logical block is delimited by newlines, comments or `if/end`, `begin/end`, `def/end`, etc. So, for example:

```crystal
a = 1
foo = 10

some_call
```

Will be formatted to:

```crystal
a   = 1
foo = 10

some_call
```

But

```crystal
a = 1
foo = 10
some_call
```

will be left as is.

And for a def:

```crystal
def initialize
  @a = 1
  @foo = 10
  @lalala = 20
end
```

would be formatted to:

```crystal
def initialize
  @a      = 1
  @foo    = 10
  @lalala = 20
end
```

The above logic is because:

* The most common case is `initialize`, where you initialize a bunch of variables. If you later have more logic you can separate that with a newline to keep the assignments aligned.
* Another common case is defining a bunch of variables before begin used in an algorithm. Separating them with a newline allows you to align them and letting the reader know they are related.
* Other consecutive assignments that happen between calls and other expressions are mostly for temporary variables, so they won't be aligned.

I tried this with some code in the standard library and the results look good. A point in favor of this is that right now there's no way to align these assignments, and with this change you have a choice: separate them in logical groups, they'll be aligned.

What do you think?

### CODE REVIEW

**Comment by ozra** [comment]
Super! :-)

**Comment by rhysd** [comment]
I tried this branch in my some projects.  It worked greatly :+1:.

**Comment by sdogruyol** [comment]
:+1:

**Comment by benoist** [comment]
:+1:

**Comment by ysbaddaden** [comment]
I don't use such alignments anymore. It's harder to read and clutters GIT patches whenever adding or removing a variable. The initialize example is symptomatic of that: remove `@lalalala` and you have a 3 line diff instead of one.

**Comment by asterite** [comment]
We finally decided not to go with this because of the reasons @ysbaddaden mentions, and also because sometimes a lot of whitespace is added and it actually makes code harder to read sometimes.

**Comment by ozra** [comment]
How about a "use formatting" and a "check in formatting" connected to a git hook. A believe this is a real good path forward for all programmers.

**Pull request closed without merging**
