### PR TITLE
Add Iterator#in_groups_of

### PR DESCRIPTION
**Pull request by PragTob**
The optional block argument is still missing, will work that out around the weekend or so :)

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! Try to make sure (add a spec) that other iterator methods (like `to_a`) work as well. For example I think it won't work right now because it's `include Iterator(T)` instead of `include Iterator(Array(T | U))` (the problem isn't evident because methods that are defined by Iterator are never instantiated if you only call `next` and `rewind`).

**Comment by PragTob** [comment]
@asterite thanks for the hint, will totally do - still gotta get used to all the cool typing after years of mostly Ruby and JavaScript :)

**Comment by PragTob** [comment]
Fixed the type annotation and added the optional block argument.

With the latter I found it easiest to add another implementation, I think the solution has a certain beauty of composition but opinions might differ. Let me know what you think :)

**Comment by asterite** [comment]
Thanks! Looks good :-)

I think the block version is not needed. Instead of:

```crystal
(1..5).each.in_groups_of(2, 0) { |elements| elements.sum }
```

You can do:

```crystal
(1..5).each.in_groups_of(2, 0).map { |elements| elements.sum }
```

In fact, if you look at the implementation of `InGroupsOfBlock` and `Map` they are the same.

I'll merge and remove the block version.

**Comment by PragTob** [comment]
Okay, good point - thanks! :)

**Pull request merged**
