### PR TITLE
Remove pending of `"\0\0".length`

### PR DESCRIPTION
**Pull request by yui-knk**
@asterite Now this test is passed. But I do not know which commit make this test case passed.

### CODE REVIEW

**Comment by jhass** [comment]
We probably change `pending` to raise if the spec passes and add `skip` or the like for stuff that causes segfaults when actually run.

**Comment by asterite** [comment]
Note that we are still on 0.7.4. If you run the specs with the current compiler, I think it crashes.

**Comment by yui-knk** [comment]
@jhass  sure `pending` method [yield nothing](https://github.com/manastech/crystal/blob/master/src/spec/dsl.cr#L33), so nothing is raised if spec was passed. I think we should change this :)

**Comment by asterite** [comment]
@yui-knk The problem is that this pending method actually produces a segfault because of a bug, so I'm not sure running pending specs is a good way.

**Comment by asterite** [comment]
Oh, I could have merged this PR, totally forgot about it. Already commited the fix.

**Pull request closed without merging**
