### PR TITLE
Update HTML::Builder library

### PR DESCRIPTION
**Pull request by davydovanton**
1. Fixed spaces between html tag attributes
2. Selected not close html tags to a separate macro
3. Add simple documentation about library

### CODE REVIEW

**Comment by bcardiff** [comment]
:+1: 

Also, macros can generate comments using the arguments. So basic documentation to tag methods can be added. 

```crystal
macro getter(name)
  # Returns the {{name}}
  def {{name}}
    @{{name}}
  end
end
```

**Comment by davydovanton** [comment]
@bcardiff wow, I don't know about this, thank! May be we also replace `#text` to `String` argument like as in [arbre](https://github.com/activeadmin/arbre)?

**Comment by bcardiff** [comment]
You mean to change the method name? I see they use `#text_node` not a bad name, but longer, I think `#text` is find.

If you mean to change the argument, since this is a short single argument method any name might work. But I try to avoid using type names as argument names. You might lose the semantic of the argument if you do so.

**Comment by davydovanton** [comment]
yes, I mead to change the argument, thanks for feedback

**Comment by davydovanton** [comment]
@bcardiff I add documentation for any methods

**Comment by bcardiff** [comment]
Thanks! We will merge it soon, yet I think it should say renders rather than returns.

Something like
```
# Renders `{{tag.id.upcase}}` html tag with any options. 
```

will generate:

Renders `A` html tag with any options.

We can change it later if you prefer. 
Thanks for the contribution!

**Comment by davydovanton** [comment]
@bcardiff thanks for review :tada:

**Comment by davydovanton** [comment]
@bcardiff thanks! :tada:

**Comment by bcardiff** [comment]
Thanks!

**Pull request merged**
