### PR TITLE
Return nil or correct value in various methods.

### PR DESCRIPTION
**Pull request by technorama**

### CODE REVIEW

**Comment by jreinert** [comment]
I'm all for it but this kind of code makes me afraid that we're going to have an obligatory return statement at some point... :/

**Comment by jreinert** [comment]
(and if it's missing return nil)

**Comment by technorama** [comment]
There are plenty of existing methods in many classes that return nil using this same pattern.  See String, IO, etc.

Most of the changes are for internal methods where the returns should never be relied upon.

The others are leaking internal state like `@in_buffer_rem` which is always incorrect.

**Comment by jreinert** [comment]
that's true

**Comment by tristil** [comment]
random thought, what if you had some kind of decorator or macro that marked a method as a command (rather than a query) and automatically returned the nil. Say `def_command` or `command def` or something?

**Comment by asterite** [comment]
I agree with some `nil` (Channel, File, IO::Buffered), but Event and Scheduler are not public API so those return types don't matter, and those `nil` just visually pollute the code. We also need to consider #1393 for this.

**Comment by ozra** [comment]
It would be neat if declaring return type Nil (is there a Nothing/None?) would implicitly assume a nil at then end, instead of throwing an error when the last expression is non nil.
I've got nil's at the end of a shitload of "procedural" methods, would be nice to drop them.

**Comment by technorama** [comment]
@asterite I'm sorry but returning nil in Scheduler is not just noise.  Some of those methods are leaking internal state right now indirectly through public methods.

```
def foo bar
  if bar
    true
  else
    spawn { nil }
  end
end

f = foo(true)
p typeof(f) #=> (Bool | Array(Fiber))
```

There's no telling where the next internal use of Scheduler of Event will end up as the last statement in a method leaking state again.  The safest way to handle this is returning an incomparable object like Void or nil if Void is not made available as in #1394.

**Comment by technorama** [comment]
@asterite The code example in my last comment should also highlight the possible problems with returning nil.  Comparisons could erroneously be decided based on a method that returns nil but really meant no usable value.

**Comment by ozra** [comment]
I 2nd the notion of a Void or Nothing return type.

**Comment by asterite** [comment]
We changed some cases, the others we don't consider them public API. In `spawn` we return the Fiber, we don't know yet if we want Fiber to be public API yet, but it's the most reasonable thing to return.

**Pull request closed without merging**
