### PR TITLE
Escaped '<' and '>' characters during the creation of documentation

### LINKED ISSUE #1067: html escape code in docs
We need to html escape the comments probably.

screen shot 2015-07-31 at 11 35 24 am

screen shot 2015-07-31 at 11 36 23 am

But ~~everything~~ crystal is awesome

### PR DESCRIPTION
**Pull request by davydovanton**
Fixed #1067 

screenshot 2015-07-31 21 13 33

/cc @bcardiff

### CODE REVIEW

**Comment by davydovanton** [comment]
@bcardiff so, I fixed `<` and `>` characters in documentation building. But I can't find tests for this :(

**Comment by bcardiff** [comment]
Thanks!

And yup, there are no test for this :-$ as @asterite said  https://github.com/manastech/crystal/issues/1067#issuecomment-126720663 . 

I'm not sure if the highlight is not broken due to the escaping. Because you are escaping all the < > and not just the one in the comments, am I right? I haven't went into the internals of those classes.

**Comment by davydovanton** [comment]
@bcardiff yes, you are right, it's broken code :sweat: 
screenshot 2015-07-31 21 29 40

**Comment by davydovanton** [comment]
@bcardiff I can to suggest use this regular expressions for parsing html tags:
``` crystal
value = "<a href=\"google.com\">crystal is awesome</a> <i class=\"\"> test"
value
  .gsub(/<((\w+)(\s.+)?)>(.*)<\/\2>/) { |s, m| "&lt;#{m[1]}&gt;#{m[4]}&lt;/#{m[2]}&gt;" }
  .gsub(/<((\w+)(\s.+)?)>/) { |s, m| "&lt;#{m[1]}&gt;" }
```

What do you think?

_I don't like this solution ( it's terrible for me ) but I can't think something else :sweat:_

**Comment by bcardiff** [comment]
Maybe what we just need is to escape the rendered code here in the [highlighter](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/highlighter.cr#L119) or only for the [comment token type](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/highlighter.cr#L28) using the gsubs in this PR.

**Pull request closed without merging**
