### PR TITLE
Macro def doc

### PR DESCRIPTION
**Pull request by jhass**
Supersedes #1317

### CODE REVIEW

**Comment by MakeNowJust** [comment]
:+1:  I will close #1317

**Comment by asterite** [comment]
Great, thanks! There's a small typo "cannot not" which I'll fix right away.

**Comment by asterite** [comment]
This broke something, because now travis won't stop triggering automatic builds...

**Comment by jhass** [comment]
@asterite try adding `[ci skip]` to https://github.com/manastech/crystal/blob/gh-pages/travis-build.sh#L13

**Comment by jhass** [comment]
I think what happened is that the builds now starting quick enough to run in parallel and you fast push with the fix caused the rebuild docs commits to undo each others change and thus triggering a new commit/build

**Comment by jhass** [comment]
In any case they should never trigger a build themselves so `[ci skip]` is the correct solution.

**Pull request merged**
