### PR TITLE
Add alias_method macro to object

### PR DESCRIPTION
**Pull request by elthariel**
It has the same limitation as delegate as you might imagine

### CODE REVIEW

**Comment by asterite** [comment]
We actually had this macro before and removed it. We don't want aliases in the language, it makes everyone having to learn a dozen of ways to do the same thing.

**Comment by asterite** [comment]
Reference: https://github.com/manastech/crystal/issues/1179#issuecomment-131267190

**Comment by elthariel** [comment]
I understand why you don't want to *use* it inside the standard library but it still makes sense to keep it available.

I'm currently working on crystal-gl. I'm generating a lot of code using script and macros with names i can't change and want to give them more convenient names in some case

**Comment by stugol** [comment]
I consider this to be kinda important.

**Comment by dsounded** [comment]
I vote for not to support `aliases`, it's make a lot of mess everywhere

**Comment by elthariel** [comment]
People *are* going to use aliases. It's just calling to have everybody have
their own implementation everywhere.

**Comment by dsounded** [comment]
@elthariel But just see, from the Ruby world, developer should know what the alias `reduce` or `inject`, `map` or `collect` - that makes life harder. I've faced up few times with something like that during debugging: well, `reduce`(first time I've seen it) what is this ? After googling only: Oh, come on, another alias, you are kidding me. :smile:

**Comment by stugol** [comment]
`reduce` makes sense. `inject` is just stupid. Don't force restrictions on programmers just to save yourself a moment's googling.

**Comment by elthariel** [comment]
It's not because there are bad use cases that there is only bad use cases

**Comment by dsounded** [comment]
Python's "only one way to do it" makes a lot of sense, I've liked Crystal for the same, at the one of Ruby Conf Batsov said that `alias_methods` is a bad part of Ruby as well, but anyway this is decision which should make @asterite and other guys from the core team.

**Comment by elthariel** [comment]
Some guy at PyCon also had a talk about how functions were better than
objects, you can find quotes saying everything, but this is dialectics.
Beside, python's mottos are often wishful thinking: Let's consider
"everything should be explicit" vs the implementation of properties.

IMO, the point is somewhere else. alias_method is trivial to implement.
It's going to happen in the user's codebases. It's better to have it and
document its shortcomings than just ignore it.

**Comment by kirbyfan64** [comment]
> everything should be explicit

It actually goes like this:

> Explicit is better than implicit.

and is eventually followed by:

> Special cases aren't special enough to break the rules.
> **Although practicality beats purity.**

Which explains properties right there.

**Comment by asterite** [comment]
@elthariel `alias_method` is not trivial to implement: named arguments won't work, neither splat nor block argument. I don't think it's good if we provide a macro in the standard library that doesn't work in all cases. In the future we will probably fix these shortcomings, but in any case I don't think aliases are a good thing. Note that this is subjective, but, well, when you design a language you have to make strong decisions most of the time.

**Comment by elthariel** [comment]
I forgot about those important details ^^. It makes sense not to have a
semi-working implementation of something. That being said, I hope the day
comes when we can implement it properly, even if I understand this is not a
priority right now.

**Comment by rubyFeedback** [comment]
I used ruby since close to 20 years.

I abandoned alias_method a long time ago. I do, however had, use "alias" a lot.

I can already simulate it via:

  def foo
  end
  def bar
    foo() # using the () just to make it clearer
  end

so using:

    alias foo bar

just saves me a few keys.

So while I don't care about alias_method, I am missing "alias"
to methods.

crystal, however had, already (!) uses aliases:

https://crystal-lang.org/reference/syntax_and_semantics/alias.html

    alias PInt32 = Pointer(Int32)

So the above statement that aliases in itself are "bad" or "impossible"
or "lead to chaos" is strange if aliases in crystal are already used as
shortcut to re-aliases types. IMO it should be possible to alias 
methods too - this is purely from an efficiency point of view.

(I think some of the discussion goes into alias_method, but
let's simply ignore the alias_method issue and focus solely
on aliases. Crystal already uses them. It feels weird to 
say crystal allows aliases to types but forbids them elsewhere.
Perhaps there could be a high-ruby compatibility mode. That
way you could still not officially support it, but allow for users
who got used to them to keep on using them in their own code
base as a compromise.)

The other parts of "aliases are the end of the world" is just pointless
opinion and ultimately FUD. It's ok to not want to add them, because
I also agree that there are trade-offs - for instance, grepping through
source code at a later point is made harder if you, like me, use really
simple editors (yup, I use a very simple, outdated editor and I get 
by just fine). But to make it based on what Ary wrote like stating 
"I don't think aliases are a good thing", without really explaining 
WHY, is ultimately just an opinion. And I disagree on it completely.

I agree about that you have to make decisions - this is correct.

I am saying that these decisions should be based on specific 
goals and objectives, and not on emotions or "my personal 
opinion is that aliases lead to the end of the world". They add
complexity indeed, but to reason that aliases are never useful,
even more so when crystal already (!!!) uses them for types,
is making this a very, very strange discussion ... even if the
decision it never changed, the rationale should be based on 
specific arguments or preferences by this or that trade-off.

**Comment by docelic** [comment]
Not to encourage your intended use of aliases, but you can see two macros that deal with aliases here:
https://github.com/crystallabs/crysterm/blob/master/src/macros.cr

The first one, `alias_method`, is a copy of the macro that was present in Crystal itself up to some point.

The second one, `alias_previous`, is a convenient way to define an alias for a method you have just defined. Something like:

```cr
def myname
  # Do something
end

alias_previous :yourname
```

**Comment by straight-shoota** [comment]
You're mixing two different but homonymic concepts. Type aliases are not to be confused with method aliases. A method alias is just a different name for another method. Crystal's philosophy is to avoid that because it's at best unnecessary and at worst causes extra friction and cognitive load.

Type aliases however are a means to give complex types (such as big union types) a name that allows identifying them efficiently.
A typical example for that is `JSON::Any::Type`:https://github.com/crystal-lang/crystal/blob/cadc4b3c7003279d93be4780afa5f0bc8e6cf6f1/src/json/any.cr#L21

It's refered to in several other places and listing all those member types of the union every time would be excruciatingly verbose. Using a type alias gives it a distinctive name which can be used as a reference.

**Pull request closed without merging**
