### PR TITLE
HTTP::Headers: Preserve input case, indifferent access between - and _

### PR DESCRIPTION
**Pull request by jhass**
Alternative to #1416

After some optimizations this is almost as fast as #1416 for the common case (storing and accessing `Content-Length`), faster for most other cases and faster than master for any case.

Semantic change: this will merge together headers with the same name that only differ in using `-` vs `_`. Technically these are separate headers, in practice you want indifferent access to both. So the first one appearing will win when it comes to serialization.

Some benchmarks, HeadersMaster is master, HeadersPR is #1416 and HeadersCompare is this PR:

```
Insert Content-Type
 HeadersMaster   1.69M (±15.98%)  1.80× slower
     HeadersPR   2.86M (±17.39%)  1.07× slower
HeadersCompare   3.05M (±19.56%)       fastest
Insert CONTENT-TYPE
 HeadersMaster   1.64M (±19.13%)  1.69× slower
     HeadersPR  520.1k (±23.25%)  5.36× slower
HeadersCompare   2.79M (±18.50%)       fastest
Insert content-type
 HeadersMaster   1.69M (±19.76%)  1.96× slower
     HeadersPR 541.97k (±23.87%)  6.10× slower
HeadersCompare    3.3M (±11.60%)       fastest
Insert Content_Type
 HeadersMaster   1.64M (±16.44%)  1.82× slower
     HeadersPR  553.5k (±19.05%)  5.39× slower
HeadersCompare   2.98M (±18.69%)       fastest
Insert CONTENT_TYPE
 HeadersMaster    1.7M (±14.48%)  1.68× slower
     HeadersPR 574.98k (±16.87%)  4.97× slower
HeadersCompare   2.86M (±21.54%)       fastest
Insert content_type
 HeadersMaster   1.57M (±21.02%)  1.99× slower
     HeadersPR 525.31k (±22.99%)  5.95× slower
HeadersCompare   3.13M (±16.99%)       fastest
Fetch CONTENT-TYPE from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster   2.73M (±19.17%)  3.65× slower
     HeadersPR 595.94k (±22.36%) 16.69× slower
HeadersCompare   9.95M (± 5.72%)       fastest
Fetch content-type from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster    2.7M (±17.70%)  6.49× slower
     HeadersPR 568.19k (±26.63%) 30.89× slower
HeadersCompare  17.55M (± 3.47%)       fastest
Fetch Content_Type from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 638.53k (±20.03%) 27.82× slower
HeadersCompare  17.77M (± 3.57%)       fastest
Fetch CONTENT_TYPE from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 625.43k (±22.81%) 14.99× slower
HeadersCompare   9.38M (± 4.55%)       fastest
Fetch content_type from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 656.86k (±22.21%) 24.08× slower
HeadersCompare  15.82M (± 2.70%)       fastest
Fetch Content-Type from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster   2.36M (±25.62%)  8.11× slower
     HeadersPR   17.9M (± 4.50%)  1.07× slower
HeadersCompare  19.12M (± 3.13%)       fastest
Fetch Content-Type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster   2.74M (±16.89%)  6.25× slower
     HeadersPR  17.11M (± 4.30%)       fastest
HeadersCompare  11.17M (± 3.40%)  1.53× slower
Fetch content-type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster   2.61M (±17.26%)  3.94× slower
     HeadersPR 696.65k (±16.09%) 14.75× slower
HeadersCompare  10.28M (± 3.33%)       fastest
Fetch Content_Type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 660.81k (±18.19%) 15.53× slower
HeadersCompare  10.27M (± 4.13%)       fastest
Fetch CONTENT_TYPE from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 610.72k (±25.72%) 24.76× slower
HeadersCompare  15.12M (± 4.79%)       fastest
Fetch content_type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 640.09k (±23.64%) 14.93× slower
HeadersCompare   9.55M (± 3.54%)       fastest
Fetch CONTENT-TYPE from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster    2.4M (±17.67%)  7.00× slower
     HeadersPR 665.95k (±19.07%) 25.24× slower
HeadersCompare  16.81M (± 3.66%)       fastest
Fetch Content-Type from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.41M (±24.80%)  7.20× slower
     HeadersPR  17.38M (± 3.14%)       fastest
HeadersCompare  16.96M (± 5.75%)  1.02× slower
Fetch CONTENT-TYPE from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.59M (±23.16%)  3.54× slower
     HeadersPR 685.06k (±17.83%) 13.40× slower
HeadersCompare   9.18M (± 2.92%)       fastest
Fetch Content_Type from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 630.89k (±21.09%) 24.02× slower
HeadersCompare  15.15M (± 4.31%)       fastest
Fetch CONTENT_TYPE from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 666.46k (±18.70%) 12.80× slower
HeadersCompare   8.53M (± 4.33%)       fastest
Fetch content_type from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 611.24k (±22.82%) 30.00× slower
HeadersCompare  18.34M (± 3.92%)       fastest
Fetch content-type from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.65M (±19.22%)  7.31× slower
     HeadersPR 691.26k (±16.60%) 28.01× slower
HeadersCompare  19.36M (± 6.91%)       fastest
Fetch Content-Type from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  17.26M (± 3.47%)  1.06× slower
HeadersCompare  18.22M (± 3.08%)       fastest
Fetch CONTENT-TYPE from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 719.83k (±11.05%) 12.79× slower
HeadersCompare    9.2M (± 2.35%)       fastest
Fetch content-type from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 693.31k (±17.06%) 22.84× slower
HeadersCompare  15.84M (± 3.39%)       fastest
Fetch CONTENT_TYPE from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster   2.75M (±19.25%)  3.59× slower
     HeadersPR 656.32k (±18.94%) 15.01× slower
HeadersCompare   9.85M (± 5.09%)       fastest
Fetch content_type from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster   2.79M (±18.51%)  6.12× slower
     HeadersPR 655.18k (±15.97%) 26.04× slower
HeadersCompare  17.06M (± 4.36%)       fastest
Fetch Content_Type from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster   2.39M (±21.84%)  7.87× slower
     HeadersPR 678.44k (±14.05%) 27.71× slower
HeadersCompare   18.8M (± 5.55%)       fastest
Fetch Content-Type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  17.67M (± 2.19%)       fastest
HeadersCompare   10.8M (± 2.54%)  1.64× slower
Fetch CONTENT-TYPE from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 606.86k (±21.74%) 25.93× slower
HeadersCompare  15.74M (± 3.14%)       fastest
Fetch content-type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 641.74k (±20.19%) 15.20× slower
HeadersCompare   9.75M (± 3.29%)       fastest
Fetch Content_Type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.53M (±17.29%)  4.32× slower
     HeadersPR 668.01k (±16.83%) 16.33× slower
HeadersCompare  10.91M (± 6.77%)       fastest

Fetch content_type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.57M (±22.43%)  3.94× slower
     HeadersPR 649.41k (±19.81%) 15.56× slower
HeadersCompare  10.11M (± 4.76%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.58M (±20.48%)  6.49× slower
     HeadersPR 634.95k (±21.47%) 26.41× slower
HeadersCompare  16.77M (± 3.19%)       fastest

Fetch Content-Type from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  17.48M (± 3.07%)       fastest
HeadersCompare  15.76M (± 2.91%)  1.11× slower

Fetch CONTENT-TYPE from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 538.37k (±21.44%) 16.39× slower
HeadersCompare   8.82M (± 3.97%)       fastest

Fetch content-type from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 661.04k (±16.49%) 28.77× slower
HeadersCompare  19.02M (± 3.02%)       fastest

Fetch Content_Type from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster   2.28M (±25.69%)  7.51× slower
     HeadersPR 526.65k (±25.17%) 32.44× slower
HeadersCompare  17.08M (± 3.43%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster   2.44M (±20.55%)  3.78× slower
     HeadersPR 597.78k (±24.74%) 15.45× slower
HeadersCompare   9.24M (± 4.77%)       fastest

Fetch content_type from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster   2.42M (±23.68%)  7.92× slower
     HeadersPR 659.33k (±16.96%) 29.10× slower
HeadersCompare  19.19M (± 6.30%)       fastest

### CODE REVIEW

**Comment by asterite** [comment]
Looks good.

My only problem with Hash's Comparator is that it should be part of the generic arguments, if we want that. Otherwise the @comp variable ends up being a union and all hashes become slow :-(

I'd prefer to remove the comparator from Hash, and then add it later once (and if) we support default values for type arguments.

Could the normalization be done without this comparator?

/cc @waj

**Comment by jhass** [comment]
Not without implementing a custom hash, the point is to do it on comparison to avoid allocations.

**Comment by asterite** [comment]
An alternative is to use a wrapper object, say `struct Header` ("private" to `HTTP::Headers`) that wraps a String and defines `hash` and `==`. Then you use `Header` as a key, and wrap strings in `Header` before comparing them.

Then of course you need to unwrap the `Header` into a `String` before returning it, making `method_missing` much harder to work, but maybe we can remove that feature for now.

Or... we can leave this the way it is now and later refactor it and optimize it. It's better if we do this because it's more important that the underscore/dash difference is fixed, we can always optimize later if we keep a compatible API/functionality. So merge if this is OK with you :-)

**Comment by jhass** [comment]
I actually just had the same idea with the wrapper struct, and it's indeed faster, I updated the benchmarks. That means we really should drop the comparator from Hash forcing people to use wrapper instead.

I didn't drop the forward yet, but I added an each overload that unwraps, since that was used in the specs and is the most used method I think.

**Comment by asterite** [comment]
Looks good! :+1:

**Comment by jreinert** [comment]
Very good indeed!

**Pull request merged**
