### PR TITLE
Add 'label' tag to HTML::Builder

### PR DESCRIPTION
**Pull request by trapped**

### CODE REVIEW

**Comment by asterite** [comment]
Should we maybe remove `HTML::Builder` from the standard library? I don't see it as a very useful class. It was nice as an experiment to see what we can do with `with ... yield`, but I guess using ECR or another template is better. I'd also like to remove some not-truly-necessary things from the standard library so we later don't have to keep them for backwards compatibility.

**Comment by omninonsense** [comment]
:+1: for removing `HTML::Builder`

**Comment by jhass** [comment]
If we would move to a distinct Github org we could simply pull out those parts into their own repos and seek maintainers for them.

**Comment by waterlink** [comment]
I like @jhass 's suggestion

--
Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

**Comment by luislavena** [comment]
@asterite perhaps is time to move crystal to it's own organization and then we can split non-essential things in separate repositories?

**Comment by omninonsense** [comment]
+2 for making a dedicated crystal org.

**Comment by ysbaddaden** [comment]
There already is an org: https://github.com/crystal-lang/ but it's unused, yet.

**Comment by sdogruyol** [comment]
:+1: for organization

**Pull request closed without merging**
