### PR TITLE
add github_name option to init config and read from global git config

### PR DESCRIPTION
**Pull request by jreinert**
this will set the creator, maintainer line in ## Contributers in the README to `- [[your-github-name]] ...` if no github.user git option is set.

I left it like that, because technically it's clear from the previous occurences of [your-github-name], that the [] are supposed to be replaced too. It would've otherwise also added unnecessary complexity to the template. (`sub(/(?<=^\[).*(?=\]$)/, ...)`)

### CODE REVIEW

**Comment by bcardiff** [comment]
I like it. And I've just set `git config --global github.user bcardiff` just in case ;-)

I didn't find any references other than https://github.com/blog/180-local-github-config regarding github.user config. Is it used by any other listed there? I don't any app that require user/token but I like the idea of not typing my username every time.

**Comment by jhass** [comment]
My git config already has it, so it was useful at some point to me though I don't remember why :D Certainly seems fairly standard for tools that need it though.

**Comment by jreinert** [comment]
dito

**Comment by asterite** [comment]
I like it, thanks!

**Pull request merged**
