### PR TITLE
Add convenience methods for accessing a strings codepoints

### PR DESCRIPTION
**Pull request by jhass**
They're really great to tinker with and quickly demonstrate
weirdnesses in Unicode.

I also documented some related methods

### CODE REVIEW

**Comment by asterite** [comment]
Awesome, thanks!!

Very nice trick documenting `Char#ord`, I didn't realize we could do it. In fact it was already documented [here](https://github.com/manastech/crystal/blob/master/src/compiler/crystal/tools/doc/primitive.cr#L19-L27), but your way is much better.

What do you think if we make `each_codepoint` just do `each_char.map(&.ord)`? It should be the same, plus it shouldn't have any performance penalty because the map iterator is a struct.

**Comment by jhass** [comment]
I thought I follow the same way `each_char` and `each_byte` are implemented, allocating an Array of the right size beforehand. Though yeah, it shouldn't matter much since you'd tend to do these only on small examples anyway so I don't care much.

**Comment by Sdogruyol** [comment]
@jhass Great job :+1:

**Comment by asterite** [comment]
@jhass I'm talking about `each_codepoint` without a block, not about `codepoints` (which I think is fine).

**Comment by asterite** [comment]
@jhass But don't worry, I'll make the change myself (it's a small change)

**Comment by jhass** [comment]
Uh, yeah I was a bit slow there, sorry.

**Pull request merged**
