### PR TITLE
Implement JSON error messages (sort of...)

### PR DESCRIPTION
**Pull request by kirbyfan64**
Now, there is a very slight issue with this PR. It seems that, for some weird reason, the error messages are now *always* JSON, even if I explicitly pass `-f text` (which *should* be the default). I have no clue why this is happening, so I was hoping for a little help here... :D

### CODE REVIEW

**Comment by asterite** [comment]
I debugged it a bit until I understood what was happening: an exception is thrown **befoe** the config can be returned, so it ends up being nil.

That `Command` module is programmed too much in a functional style. It would be nice, if you feel like doing that, to instantiate a `Command` instance and then evaluate the options (that is, `Command.run` would instantiate a `Command`, etc.). That way you can store the config in a `@config` variable and have it available everywhere.

**Comment by kirbyfan64** [comment]
@asterite Got that! I'll work on it next chance I get!

**Comment by k2b6s9j** [comment]
:+1:

**Comment by kirbyfan64** [comment]
@asterite For the sake of time, I just used a simple workaround. It should work correctly now.

**Comment by asterite** [comment]
@kirbyfan64 Looks almost good. I'm seeing that only one entry is generated. But for example:

```crystal
def foo
  bar
end

def bar
  baz
end

foo
```

Gives this error:

```
Error in ./foo.cr:9: instantiating 'foo()'

foo
^~~

in ./foo.cr:2: instantiating 'bar()'

  bar
  ^~~

in ./foo.cr:6: undefined local variable or method 'baz' (did you mean 'bar'?)

  baz
  ^~~
```

So I would expect the generated JSON to be an array of three entries. You can access this with the `@inner` variable.

Also, instead of generating an intermediate Hash and invoking `to_json` you can use [JSON::Builder](http://crystal-lang.org/api/JSON/Builder.html).

**Comment by asterite** [comment]
Ummm... I don't know what happened, but it seems I merged this accidentally :blush:

@kirbyfan64 If you want to try to improve the behaviour to what I described above, please do it :-)

**Comment by kirbyfan64** [comment]
@asterite Haha, I'll just open up a new PR later. :)

**Pull request merged**
