### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by vyp**
---

The second one is a typo right? Unless I misunderstood something.

PS - I did `rake build`, but that ended up additionally changing all the timestamps of the generated book, which I'm pretty sure you don't want? So I'm assuming you will have to rebuild the book yourself?

### CODE REVIEW

**Comment by vyp** [comment]
By the "second one", I mean the fix for `type_restrictions.md` (It's not the second one anymore because I added some more fixes.)

**Comment by vyp** [comment]
I just changed all instances of '--hierarchy' with 'hierarchy' instead. Because I'm assuming it got changed to a command or something, but it wasn't updated in the docs? (Because running with `--hierarchy` I get `Error: unknown command: --hierarchy`.) If this is not correct and I missed something then just tell me to revert that.

**Comment by vyp** [comment]
Pretty sure that should be "exits" and not "exists" in `block_and_procs.md`.

**Comment by vyp** [comment]
Hmm I overwrote a commit (per @ysbaddaden's advice), and his comment disappeared: https://github.com/vyp/crystal/commit/055fb0595bffd42e379da83e907e7a77211c9813#commitcomment-11588095

**Comment by vyp** [comment]
@ysbaddaden Could I have done that better (whilst keeping a single commit)?

**Comment by vyp** [comment]
Actually, I think it's because @ysbaddaden commented on the *commit*, not this thread per se, so I think I was correct.

**Comment by ysbaddaden** [comment]
@vyp don't worry, since you made the change my comment could be discarded ;-)

**Comment by asterite** [comment]
Thanks!!

**Pull request merged**
