### PR TITLE
allow nil values in record

### PR DESCRIPTION
**Pull request by kostya**

### CODE REVIEW

**Comment by jhass** [comment]
I'm not sure that's a good default. Maybe we can make it explicit? Something like

```cr
record Foo, required_field, optional_field?
```

**Comment by asterite** [comment]
I'm not sure about this either. What's your use case?

**Comment by kostya** [comment]
brainfuc interepter:

```ruby
record Op, op, subtree
...
  iterator.each do |c|
    op = case c 
      when '+'; Op.new(:inc, nil)
      when '-'; Op.new(:dec, nil)
      when '>'; Op.new(:movef, nil)
      when '<'; Op.new(:moveb, nil)
      when '.'; Op.new(:print, nil)
      when '['; Op.new(:loop, parse(iterator))
      when ']'; break;
    end

    res << op if op
  end```

**Comment by asterite** [comment]
In that case I'd prefer to do this:

```crystal
record Record1, a, b do
  def initialize(@a)
  end
end

p Record1.new(1, 2)
p Record1.new(3)
```

The problem with nil is that if you forget to pass an argument you'll get an error in the place where you access that property. I find the above snippet, or an explicit nil, preferable.

I also think the use case for `record` is like a tuple, but with names instead of indices. Since a tuple has a fixed size, I see record the same way. Allowing to create a record with less elements seems odd.

**Pull request closed without merging**
