### PR TITLE
Futures on objects.  Solves some issues raised in #1589.

### PR DESCRIPTION
**Pull request by technorama**

### CODE REVIEW

**Comment by ysbaddaden** [comment]
I like this better than having many global macros —I'd love to keep only the keywordish `spawn` macro. But what about a Future module that could be included in classes that want to go concurrent?

**Comment by technorama** [comment]
@ysbaddaden You mean actors?  Working on that.

**Comment by ysbaddaden** [comment]
I meant "instead of pushing them to Object", but yeah, actors.

**Comment by technorama** [comment]
`future { }` is needed in addition to `obj.future.foo`.

```
  future { 2 ** 128 }
  foo.future.long_calculation
```

It may also be needed in main.

**Comment by asterite** [comment]
I know this PR is for taking the concurrency model/API in another way, but we don't want to go that way, so from my side it's a no. I'll check with @waj, but I think he also agrees with me (or, better said, I agree with him :-P)

**Comment by technorama** [comment]
@asterite, @waj It would be nice if all reasons would be considered rather than using single reason rejections.  This PR started from trying to implement named Fibers for scheduler debugging which had nothing to do with changing the concurrency model.  Several times I've patched my crystal to support named fibers when working on anything involving the scheduler such as
* The event system and `wait_readable`/`wait_writable`.
* Debugging fork issues (Process.spawn development, #1273, #1295).
* Debugging sleep issues (#1295).
* Debugging IO issues (#1353, #1259).
* Debugging futures (#1527).

Scheduler inspecting and debugging was the root of this PR but not the only reason.  While attempting to implement named fibers by passing argument to `spawn` I ran into an issue discussed in #1589 - mainly that `spawn method(arg)` was inconsistent and other uses of `spawn {}` were potentially error prone and unintuitive.  **Making spawn usage more intuitive and consistent with fewer errors is the main reason for this PR**.

This PR has nothing to do with changing the concurrency model.  Rejecting this for the wrong reason(s) is no copado.

If you are rejecting this as an attempt to slow my development of a concurrent crystal don't bother.   It won't slow me as I can patch Fiber by setting  Fiber.name elsewhere (not in the constructor) as I've always done.   It's also unnecessary.  You made it clear design was not welcome but bugfixes and documentation fixes are.   I've focused my energy elsewhere.

**Comment by waj** [comment]
We've been reviewing this, but I don't like to have these methods on every object.

**Comment by technorama** [comment]
@waj This is an attempt to fix the ambiguity and error prone usage of spawn highlighted in #1589.   Keep in mind this is identical to the syntax in Celluloid.

Do you have another solution?

**Comment by asterite** [comment]
@technorama Please rewrite [channel_primes](https://github.com/manastech/crystal/blob/master/samples/channel_primes.cr) using your proposed solution.

**Pull request closed without merging**
