### PR TITLE
Env

### PR DESCRIPTION
**Pull request by will**
Documentation, error checking and a return value for set, and a few new methods.

### CODE REVIEW

**Comment by will** [comment]
Interesting, the spec failures only happen when all the specs are ran. Just running env_spec in isolation is fine

**Comment by technorama** [comment]
@will The specs failed from specific environment variables.  I sent you a PR.

**Comment by will** [comment]
@technorama wow nice catches, thanks!

**Comment by asterite** [comment]
Thanks!! it's so nice to see the standard library getting more specs and docs :-)

I think the bug that @technorama fixed has to do with #1070 . We'll soon deal with that :-)

**Pull request merged**
