### PR TITLE
add zsh completion

### PR DESCRIPTION
**Pull request by will**
~~A few things missing, but mostly there. I couldn't figure out how to get files to live at the top level with the commands though, but using `alias cr='crystal run'` fixes that.~~ Goes with https://github.com/manastech/homebrew-crystal/pull/6

### CODE REVIEW

**Comment by will** [comment]
I got help on the [zsh mailing list](http://www.zsh.org/mla/workers/2015/msg01902.html) and now the only thing that's missing is a bit of help text on `crystal init` and doing the commas on the different emit types, but that's pretty good I think.

**Comment by asterite** [comment]
Hi @will ! I know nothing about zsh so I can't really comment on this one, but if anyone knows about this and think this is OK, I'll gladly merge the pull request.

Maybe we can put that `.zsh` file somewhere else that's more visible? Maybe a `tools` or `etc` at the top-level? I don't think ti should go in the compiler's source code.

**Comment by will** [comment]
Hey @asterite moved it to /etc

Also here is a sort of screen recording http://showterm.io/58a40fee6d272bd118b32#fast note how it knows not to complete the .notcr file, and has all the options and stuff.

**Comment by jhass** [comment]
I'm neither an expert in that area, but hardcoding all the options into the completion file feels a bit odd, is there no way to parse the help output?

**Comment by jhass** [comment]
Hmm, looking through my `/usr/share/zsh` apparently everybody does it that way. I still wonder if we maybe should use a template to generate it, keeping it in sync with every change in the CLI tool seems like a headache.

**Comment by will** [comment]
Maybe a template would work, but I'm not sure how much time that'd actually save in the long run.

**Comment by jhass** [comment]
Well, with just 4efb5ad0cc4e8ae2b474193fb83fd27267e21e1e this PR is already outdated.

**Comment by will** [comment]
Sure, but in that case, were this checked in, it would have been caught when you grep the codebase to to do the find/replace.

If it were generated, when would the generation be run? On each commit, and check the result in? In the makefile? Just during packaging, wherever that happens? I'm not saying it shouldn't be generated, just curious where the step is shifted to.

**Comment by jhass** [comment]
I'd do it during packaging.

**Comment by asterite** [comment]
I think for now we can update it manually, commands don't change that often. Thanks @will !

**Comment by asterite** [comment]
@will We just released 0.7.6 but it won't come with zsh completion because of [this](https://github.com/manastech/omnibus-crystal/issues/1). We'll fix that for the next release.

**Pull request merged**
