### PR TITLE
Base64 for non-UTF8

### PR DESCRIPTION
**Pull request by jhass**
`Base64.encode` already happily accepts all your byte sequence needs by duck typing on `to_slice`. However we can only get back, potentially invalid, strings. This PR remedies that.

* Rename Base64.decode to Base64.decode_string
* Add Base64.decode returning a Slice(UInt8)

### CODE REVIEW

**Comment by asterite** [comment]
I would leave decode to return a string, and add decode_slice in any case. Is this an issue only for bcrypt?

**Comment by waj** [comment]
I think the primary goal of base64 is convert binary data to text, so my vote is `decode` returns a slice. I'd remove `decode_string` altogether but sometimes is convenient.

**Comment by jhass** [comment]
No, in fact I'm not even sure if BCrypt should work on the string or not. I made the primary `decode` return the slice because it's in fact the more common usecase for Base64, encoding byte sequences that aren't valid ASCII and most likely not valid UTF8 either for protocols that can only handle ASCII. Think public and private RSA keys, X502 certificates, PGP armored messages and so on... and there @waj beat me to it ;)

**Comment by waj** [comment]
The only use of base64 to encode strings that I remember right now is for http basic auth. Maybe someone thought base64 as an encryption algorithm there? :-P

**Comment by asterite** [comment]
Sounds good

**Pull request merged**
