### PR TITLE
Add ip address to REMOTE_ADDR Header

### PR DESCRIPTION
**Pull request by benoist**

### CODE REVIEW

**Comment by jhass** [comment]
I'm not sure we should expose this as a header, see also #453

**Comment by benoist** [comment]
I was also thinking what the best place would be. In the framework I'm writing it looks for that header value if it's passed by a proxy, but if requests are served directly it doesn't have access to it.

https://github.com/benoist/carbon-crystal/blob/master/src/carbon_dispatch/request.cr

It would be easy to rewrite it using a remote_ip method on the HTTP::Request.

I was thinking about adding it to the from_io method, but that requires the higher IO object and not a IPSocket object. I think that should be kept like that so you can read requests from non IP sockets.

So should we create a remote_ip property for the HTTP::Request?

**Comment by jhass** [comment]
It's where I tend to too yes, probably should even name it `peer_ip` internally and have an API like `remote_ip(trust_headers=true)`

**Comment by benoist** [comment]
Whoops, messing up the commits here.

**Pull request closed without merging**
