### PR TITLE
Run crystal script without extension

### PR DESCRIPTION
**Pull request by MakeNowJust**

### CODE REVIEW

**Comment by jhass** [comment]
I don't think this is a good idea, sorry. I can easily imagine not intuitive behavior as commands are added, renamed or removed.

**Comment by waterlink** [comment]
Agree to @jhass on this one

--
Best Regards,
Oleksii Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

**Comment by MakeNowJust** [comment]
@jhass Todays `crystal` command can run the file having no extension as first argument if the file's name is not subcommand. How do you think about it?

(I think it is awesome behavior, because we can add subcommand to `crystal` and we can operate crystal project only by `crystal` completely.)

**Comment by jhass** [comment]
Yes, it's very unlikely that we'll add a command named `run.cr`.

**Comment by ysbaddaden** [comment]
I would rather have GIT like behavior for subcommands: executables prefixed with `crystal-` available in the PATH or a libexec directory.

I also prefer to have an executable file with the shebang `#! crystal eval` for local commands.

**Comment by luislavena** [comment]
I'm actually biased towards git-like style prefixed executable. That was my first idea for integrating Shards with Crystal (so the code doesn't need to be embedded).

I think that approach with prefixed or libexec directory sounds better alternative.

**Comment by MakeNowJust** [comment]
Yes, I have thought git like approach is better too. However, this approach has some bad points (e.g. duplicate command name in global, how we treat it? btw, this pr effects locally, so I think better.)

If you take practical idea for this, please open new issue ;)

**Pull request closed without merging**
