### PR TITLE
Add SemanticVersion class and specs.

### PR DESCRIPTION
**Pull request by technorama**
Suggestions on how to make the current version available and under what namespace are appreciated.

```
VERSION
Crystal::VERSION
Crystal::Config::VERSION
```

### CODE REVIEW

**Comment by asterite** [comment]
Why is this needed in the standard library?

**Comment by technorama** [comment]
* Version checking for compatibility
* Version checking of each library or shard.
* Usage within crystal-shards or another version manager for specifying and locking versions.

```
if Crystal::VERSION >= "1.3"
  use feature x
end
```

```
if Crystal::VERSION < "1.0.2"
  def compatibility_method
    ...
  end
end
````


```
  if LibFoo::VERSION >= "x.y.z" ...
```

* Usage within crystal-shards shards or whichever version manager for specifying and locking versions.

**Comment by ysbaddaden** [comment]
Your examples won't compile. You can't declare a def within a conditional. You can't have calls to different methods depending on a runtime condition : any method won't exist at compile time, ...

Shards doesn't enforce semver (too strict) and already has logic for comparing versions. This class may be more optimized, but it's also a lot of code to read and maintain.

**Comment by technorama** [comment]
@ysbaddaden the examples were pseudo code.  They weren't meant to indicate runtime conditionals especially since the crystal/library versions are fixed at compile time.

It may also be used for c libraries such as openssl with `SSLeay_version` although it would need a permissive mode as openssl versions are not quite semver compatibile.

Semver would be useful in shards.  While this PR doesn't contain ~> or >= comparisons for "1.3" it could be with a few additional lines.

Also, the semver comparisons in shards aren't semver spec compatible.

**Comment by asterite** [comment]
For checking lib versions we'll probably provide a way using [crystal_lib](https://github.com/manastech/crystal_lib) (which we'll eventually integrate in the compiler). Having CRYSTAL_VERSION is a constant accessible by `ifdef` and macros is a good idea, not sure it'll be a type, maybe just a string, I don't know. We also plan revamping `ifdef` to be a bit more powerful.

Please wait for me and @waj to review this together.

**Comment by technorama** [comment]
@asterite How would you compare "1.13.11" > "1.9.9" if the version is just a string?  13 is less than 9 when comparing strings.  You have to be prepared for backward compatible code that will require version checks beyond simple equality checks.  

The `SemanticVersion` class isn't just for crystal's internal use but for use in various protocols and libraries that use semantic version and would benefit from version comparisons.

```
server_version = SemanticVersion.new(io.gets)
if server_version >= "2.0.0"
  # use protocol v2
elsif server_version >= "1.5.1"
  # v1.5.0 is buggy and unsupported
  # use protocol v1.5
else
  raise "server version too old"
end
```

Enhancing ifdef helps in 1 and only 1 situation.  It doesn't help when comparing versions stored in files or remote services.

**Comment by ozra** [comment]
Ahh, me <3 SemVer, haha.

**Pull request merged**
