### PR TITLE
normalize dash/underscore separated http header names correctly

### PR DESCRIPTION
**Pull request by jreinert**
``` ruby
require "http/client"

headers = HTTP::Headers {"CONTENT_TYPE" => "a", "content-length" => "24", "X-Forwarded-For" => "nobody"}
pp headers
serialized = String.build do |io|
  request = HTTP::Request.new("GET", "/", headers)
  request.to_io(io)
end

puts serialized
```
Output Before:

```
headers = HTTP::Headers{"Content_type" => "a", "Content-length" => "24", "X-forwarded-for" => "nobody"}
GET / HTTP/1.1
Content_type: a
Content-length: 24
X-forwarded-for: nobody
```

Output After:

```
headers = HTTP::Headers{"Content-Type" => "a", "Content-Length" => "24", "X-Forwarded-For" => "nobody"}
GET / HTTP/1.1
Content-Type: a
Content-Length: 24
X-Forwarded-For: nobody
```

### CODE REVIEW

**Comment by jhass** [comment]
Could you please try to add some specs? You also might want to look into https://help.github.com/articles/changing-author-info/ ;)

**Comment by jhass** [comment]
Looks like we broke some specs here https://travis-ci.org/manastech/crystal/jobs/79295862#L433

**Comment by asterite** [comment]
But it seems underscores are valid in HTTP headers: http://stackoverflow.com/questions/22856136/why-underscores-are-forbidden-in-http-header-names

**Comment by ysbaddaden** [comment]
They're allowed but dropped by both Apache and NGINX by default, and it seems very common to make the translation, so maybe we can just make it too? No strong opinion, thought.

**Comment by jreinert** [comment]
I think the most troubling issue with the implementation before these changes is that "Foo-Bar" becomes "Foo-bar"

**Comment by jhass** [comment]
So the alternative I see to solve the issue is to retain the input casing and only normalize while comparing/fetching. A possible solution could look like this (patch against master):

```diff
diff --git a/spec/std/http/headers_spec.cr b/spec/std/http/headers_spec.cr
index 3ccd29a..eecabd3 100644
--- a/spec/std/http/headers_spec.cr
+++ b/spec/std/http/headers_spec.cr
@@ -12,6 +12,23 @@ describe HTTP::Headers do
     headers["foo"].should eq("bar")
   end
 
+  it "it allows indifferent access for underscore and dash separated keys" do
+    headers = HTTP::Headers{"foo_Bar": "bar", "Foobar-foo": "baz"}
+    headers["foo-bar"].should eq("bar")
+    headers["foobar_foo"].should eq("baz")
+  end
+
+  it "should retain the input casing" do
+    headers = HTTP::Headers{"FOO_BAR": "bar", "Foobar-foo": "baz"}
+    serialized = String.build do |io|
+      headers.each do |name, values|
+        io << name << ": " << values.first << ";"
+      end
+    end
+
+    serialized.should eq("FOO_BAR: bar;Foobar-foo: baz;")
+  end
+
   it "is gets with []?" do
     headers = HTTP::Headers.new
     headers["foo"]?.should be_nil
@@ -35,7 +52,7 @@ describe HTTP::Headers do
 
   it "fetches with block" do
     headers = HTTP::Headers.new
-    headers.fetch("foo") { |k| "#{k}baz" }.should eq("Foobaz")
+    headers.fetch("foo") { |k| "#{k}baz" }.should eq("foobaz")
 
     headers["Foo"] = "bar"
     headers.fetch("foo") { "baz" }.should eq("bar")
@@ -101,7 +118,7 @@ describe HTTP::Headers do
   end
 
   it "does to_s" do
-    headers = HTTP::Headers{"foo": "bar", "baz": ["a", "b"]}
-    headers.to_s.should eq(%(HTTP::Headers{"Foo" => "bar", "Baz" => ["a", "b"]}))
+    headers = HTTP::Headers{"Foo_quux": "bar", "Baz-Quux": ["a", "b"]}
+    headers.to_s.should eq(%(HTTP::Headers{"Foo_quux" => "bar", "Baz-Quux" => ["a", "b"]}))
   end
 end
diff --git a/spec/std/http/request_spec.cr b/spec/std/http/request_spec.cr
index 0f0921f..e124569 100644
--- a/spec/std/http/request_spec.cr
+++ b/spec/std/http/request_spec.cr
@@ -17,7 +17,7 @@ module HTTP
       request = Request.new "POST", "/", body: "thisisthebody"
       io = StringIO.new
       request.to_io(io)
-      io.to_s.should eq("POST / HTTP/1.1\r\nContent-length: 13\r\n\r\nthisisthebody")
+      io.to_s.should eq("POST / HTTP/1.1\r\nContent-Length: 13\r\n\r\nthisisthebody")
     end
 
     it "parses GET" do
diff --git a/spec/std/http/response_spec.cr b/spec/std/http/response_spec.cr
index bf7ef3d..255eec7 100644
--- a/spec/std/http/response_spec.cr
+++ b/spec/std/http/response_spec.cr
@@ -105,7 +105,7 @@ module HTTP
       response = Response.new(200, "hello", headers)
       io = StringIO.new
       response.to_io(io)
-      io.to_s.should eq("HTTP/1.1 200 OK\r\nContent-type: text/plain\r\nContent-length: 5\r\n\r\nhello")
+      io.to_s.should eq("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 5\r\n\r\nhello")
     end
 
     it "sets content length from body" do
@@ -117,21 +117,21 @@ module HTTP
       response = Response.not_found
       io = StringIO.new
       response.to_io(io)
-      io.to_s.should eq("HTTP/1.1 404 Not Found\r\nContent-type: text/plain\r\nContent-length: 9\r\n\r\nNot Found")
+      io.to_s.should eq("HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\nContent-Length: 9\r\n\r\nNot Found")
     end
 
     it "builds default ok response" do
       response = Response.ok("text/plain", "Hello")
       io = StringIO.new
       response.to_io(io)
-      io.to_s.should eq("HTTP/1.1 200 OK\r\nContent-type: text/plain\r\nContent-length: 5\r\n\r\nHello")
+      io.to_s.should eq("HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 5\r\n\r\nHello")
     end
 
     it "builds default error response" do
       response = Response.error("text/plain", "Error!")
       io = StringIO.new
       response.to_io(io)
-      io.to_s.should eq("HTTP/1.1 500 Internal Server Error\r\nContent-type: text/plain\r\nContent-length: 6\r\n\r\nError!")
+      io.to_s.should eq("HTTP/1.1 500 Internal Server Error\r\nContent-Type: text/plain\r\nContent-Length: 6\r\n\r\nError!")
     end
   end
 end
diff --git a/src/http/headers.cr b/src/http/headers.cr
index 725b4f6..219a6dd 100644
--- a/src/http/headers.cr
+++ b/src/http/headers.cr
@@ -1,6 +1,41 @@
 struct HTTP::Headers
+  module HeaderComparator
+    def self.hash(key)
+      h = 0
+      key.each_byte do |c|
+        c = normalize_byte(c)
+        h = 31 * h + c
+      end
+      h
+    end
+
+    def self.equals?(key1, key2)
+      return false if key1.bytesize != key2.bytesize
+
+      cstr1 = key1.to_unsafe
+      cstr2 = key2.to_unsafe
+
+      key1.bytesize.times do |i|
+        byte1 = normalize_byte(cstr1[i])
+        byte2 = normalize_byte(cstr2[i])
+
+        return false if byte1 != byte2
+      end
+    end
+
+    private def self.normalize_byte(byte)
+      if 'A' <= byte.chr <= 'Z'
+        byte + 32
+      elsif byte.chr == '_'
+        '-'.ord
+      else
+        byte
+      end
+    end
+  end
+
   def initialize
-    @hash = {} of String => Array(String)
+    @hash = Hash(String, Array(String)).new(HeaderComparator)
   end
 
   def []=(key, value : String)
@@ -8,7 +43,7 @@ struct HTTP::Headers
   end
 
   def []=(key, value : Array(String))
-    @hash[key_name(key)] = value
+    @hash[key] = value
   end
 
   def [](key)
@@ -16,32 +51,32 @@ struct HTTP::Headers
   end
 
   def []?(key)
-    values = @hash[key_name(key)]?
+    values = @hash[key]?
     values ? concat(values) : nil
   end
 
   def add(key, value : String)
-    existing = @hash[key_name(key)]?
+    existing = @hash[key]?
     if existing
       existing << value
     else
-      @hash[key_name(key)] = [value]
+      @hash[key] = [value]
     end
     self
   end
 
   def add(key, value : Array(String))
-    existing = @hash[key_name(key)]?
+    existing = @hash[key]?
     if existing
       existing.concat value
     else
-      @hash[key_name(key)] = value
+      @hash[key] = value
     end
     self
   end
 
   def fetch(key)
-    values = @hash.fetch key_name(key)
+    values = @hash.fetch key
     concat values
   end
 
@@ -50,13 +85,12 @@ struct HTTP::Headers
   end
 
   def fetch(key)
-    k = key_name(key)
-    values = @hash[k]?
-    values ? concat(values) : yield k
+    values = @hash[key]?
+    values ? concat(values) : yield key
   end
 
   def has_key?(key)
-    @hash.has_key? key_name(key)
+    @hash.has_key? key
   end
 
   def empty?
@@ -64,7 +98,7 @@ struct HTTP::Headers
   end
 
   def delete(key)
-    values = @hash.delete key_name(key)
+    values = @hash.delete key
     values ? concat(values) : nil
   end
 
@@ -82,7 +116,7 @@ struct HTTP::Headers
     return false unless @hash.size == other.size
 
     other.each do |key, value|
-      this_value = @hash[key_name(key)]?
+      this_value = @hash[key]?
       if this_value
         case value
         when String
@@ -101,11 +135,11 @@ struct HTTP::Headers
   end
 
   def get(key)
-    @hash[key_name(key)]
+    @hash[key]
   end
 
   def get?(key)
-    @hash[key_name(key)]?
+    @hash[key]?
   end
 
   def dup
@@ -141,29 +175,6 @@ struct HTTP::Headers
 
   forward_missing_to @hash
 
-  private def key_name(key)
-    if needs_capitalize?(key)
-      key.capitalize
-    else
-      key
-    end
-  end
-
-  private def needs_capitalize?(key)
-    return false if key.empty?
-
-    cstr = key.to_unsafe
-    return true unless 'A' <= cstr[0].chr <= 'Z'
-
-    i = 1
-    while i < key.bytesize
-      return true if 'A' <= cstr[i].chr <= 'Z'
-      i += 1
-    end
-
-    false
-  end
-
   private def cast(value : String)
     [value]
   end
```

Now whether that's more correct or less is largely opinion, I'd tend to say yes but at the end of the day it boils down to opinion. It appears to be the fastest variant for the majority of the cases while supporting all cases too, however this PR beats it on the common case of inserting and fetching in standard capitalization. Note the fetching benchmark doesn't factor in the cost of insertion.

```

Insert Content-Type
 HeadersMaster   1.51M (±14.43%)  1.69× slower
     HeadersPR   2.54M (± 9.78%)       fastest
HeadersCompare   2.14M (±10.08%)  1.19× slower

Insert CONTENT-TYPE
 HeadersMaster   1.54M (± 9.68%)  1.30× slower
     HeadersPR 588.49k (±10.02%)  3.41× slower
HeadersCompare   2.01M (±12.71%)       fastest

Insert content-type
 HeadersMaster   1.52M (± 8.99%)  1.34× slower
     HeadersPR 576.77k (±11.09%)  3.53× slower
HeadersCompare   2.04M (±10.09%)       fastest

Insert Content_Type
 HeadersMaster   1.49M (±10.45%)  1.40× slower
     HeadersPR 564.95k (± 9.86%)  3.68× slower
HeadersCompare   2.08M (± 9.09%)       fastest

Insert CONTENT_TYPE
 HeadersMaster   1.49M (±10.79%)  1.36× slower
     HeadersPR 561.77k (±11.83%)  3.62× slower
HeadersCompare   2.03M (±11.62%)       fastest

Insert content_type
 HeadersMaster   1.55M (± 9.63%)  1.33× slower
     HeadersPR 575.18k (± 9.84%)  3.59× slower
HeadersCompare   2.06M (±12.38%)       fastest

Fetch CONTENT-TYPE from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster   2.64M (±11.09%)  1.23× slower
     HeadersPR 707.74k (±10.02%)  4.61× slower
HeadersCompare   3.26M (± 1.25%)       fastest

Fetch content-type from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster   2.67M (± 9.71%)  1.21× slower
     HeadersPR 672.25k (±10.31%)  4.80× slower
HeadersCompare   3.23M (± 1.63%)       fastest

Fetch Content_Type from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 669.05k (±10.04%)  4.85× slower
HeadersCompare   3.25M (± 1.21%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 676.27k (±10.61%)  4.95× slower
HeadersCompare   3.35M (± 1.59%)       fastest

Fetch content_type from HTTP::Headers { "Content-Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 709.85k (± 9.50%)  4.66× slower
HeadersCompare   3.31M (± 1.41%)       fastest

Fetch Content-Type from HTTP::Headers { "Content-Type" => "bar" }
 HeadersMaster    2.5M (±10.36%)  6.88× slower
     HeadersPR  17.22M (± 1.46%)       fastest
HeadersCompare   3.25M (± 1.34%)  5.30× slower

Fetch Content-Type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster   2.44M (±10.37%)  6.34× slower
     HeadersPR  15.48M (± 2.28%)       fastest
HeadersCompare   3.21M (± 1.08%)  4.83× slower

Fetch content-type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster    2.3M (±11.44%)  1.39× slower
     HeadersPR 685.08k (±11.17%)  4.67× slower
HeadersCompare    3.2M (± 1.30%)       fastest

Fetch Content_Type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 665.14k (±11.76%)  4.94× slower
HeadersCompare   3.29M (± 2.90%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 674.74k (±12.21%)  4.89× slower
HeadersCompare    3.3M (± 1.38%)       fastest

Fetch content_type from HTTP::Headers { "CONTENT-TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 687.86k (±10.23%)  4.75× slower
HeadersCompare   3.27M (± 1.69%)       fastest

Fetch CONTENT-TYPE from HTTP::Headers { "CONTENT-TYPE" => "bar" }
 HeadersMaster   2.37M (±13.13%)  1.36× slower
     HeadersPR 673.88k (±11.01%)  4.78× slower
HeadersCompare   3.22M (± 1.82%)       fastest

Fetch Content-Type from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.45M (±12.38%)  6.29× slower
     HeadersPR  15.42M (± 1.79%)       fastest
HeadersCompare   3.17M (± 2.05%)  4.86× slower

Fetch CONTENT-TYPE from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.57M (±13.04%)  1.26× slower
     HeadersPR 689.03k (±10.42%)  4.68× slower
HeadersCompare   3.23M (± 1.28%)       fastest

Fetch Content_Type from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 668.14k (±11.87%)  4.82× slower
HeadersCompare   3.22M (± 1.35%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR    702k (±10.64%)  4.67× slower
HeadersCompare   3.28M (± 1.41%)       fastest

Fetch content_type from HTTP::Headers { "content-type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 683.62k (±10.47%)  4.73× slower
HeadersCompare   3.24M (± 1.79%)       fastest

Fetch content-type from HTTP::Headers { "content-type" => "bar" }
 HeadersMaster   2.43M (±14.15%)  1.31× slower
     HeadersPR 697.32k (±11.99%)  4.57× slower
HeadersCompare   3.18M (± 2.83%)       fastest

Fetch Content-Type from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  15.53M (± 1.59%)       fastest
HeadersCompare   3.22M (± 1.23%)  4.83× slower

Fetch CONTENT-TYPE from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 692.88k (±10.64%)  4.72× slower
HeadersCompare   3.27M (± 1.36%)       fastest

Fetch content-type from HTTP::Headers { "Content_Type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 694.55k (±10.25%)  4.58× slower
HeadersCompare   3.18M (± 2.55%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster   2.34M (±14.86%)  1.42× slower
     HeadersPR 672.74k (±11.68%)  4.92× slower
HeadersCompare   3.31M (± 1.93%)       fastest

Fetch content_type from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster   2.12M (±12.43%)  1.54× slower
     HeadersPR 683.71k (±11.75%)  4.76× slower
HeadersCompare   3.25M (± 1.61%)       fastest

Fetch Content_Type from HTTP::Headers { "Content_Type" => "bar" }
 HeadersMaster    2.5M (±11.62%)  1.32× slower
     HeadersPR 669.06k (±11.82%)  4.96× slower
HeadersCompare   3.32M (± 1.35%)       fastest

Fetch Content-Type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  15.73M (± 1.30%)       fastest
HeadersCompare   3.24M (± 1.53%)  4.85× slower

Fetch CONTENT-TYPE from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 654.57k (±13.57%)  5.01× slower
HeadersCompare   3.28M (± 2.20%)       fastest

Fetch content-type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 641.03k (±11.78%)  5.00× slower
HeadersCompare   3.21M (± 2.38%)       fastest

Fetch Content_Type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.34M (±12.06%)  1.40× slower
     HeadersPR 652.74k (±12.25%)  5.00× slower
HeadersCompare   3.26M (± 2.48%)       fastest

Fetch content_type from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.53M (±11.94%)  1.30× slower
     HeadersPR 662.89k (±12.61%)  4.96× slower
HeadersCompare   3.29M (± 2.85%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "CONTENT_TYPE" => "bar" }
 HeadersMaster   2.41M (±14.57%)  1.39× slower
     HeadersPR 654.27k (±13.47%)  5.13× slower
HeadersCompare   3.36M (± 0.97%)       fastest

Fetch Content-Type from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR  15.67M (± 1.23%)       fastest
HeadersCompare   3.22M (± 1.22%)  4.87× slower

Fetch CONTENT-TYPE from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 665.97k (±11.42%)  4.89× slower
HeadersCompare   3.26M (± 1.59%)       fastest

Fetch content-type from HTTP::Headers { "content_type" => "bar" }
Unsupported by HeadersMaster
     HeadersPR 683.52k (±11.12%)  4.67× slower
HeadersCompare   3.19M (± 1.22%)       fastest

Fetch Content_Type from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster      2M (±11.41%)  1.63× slower
     HeadersPR 631.39k (±12.31%)  5.15× slower
HeadersCompare   3.25M (± 2.13%)       fastest

Fetch CONTENT_TYPE from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster   2.45M (±12.41%)  1.36× slower
     HeadersPR 661.17k (±12.14%)  5.02× slower
HeadersCompare   3.32M (± 1.19%)       fastest

Fetch content_type from HTTP::Headers { "content_type" => "bar" }
 HeadersMaster   2.48M (±12.15%)  1.31× slower
     HeadersPR  650.5k (±11.79%)  5.02× slower
HeadersCompare   3.26M (± 2.37%)       fastest

**Comment by ysbaddaden** [comment]
I like your solution. Can we optimize so inserting/fetching `Content-Type` is the fastest operation (most common), versus the normalization of underscores and lowercases?

**Comment by jhass** [comment]
I think it's mainly slower because normalization happens on each access, that's why I tried to choose the normalization that requires the least amount of state. Normalizing to `Content-Type` will require looking at the previous char (+1 access and +1-2 comparisons for each byte)

**Comment by jhass** [comment]
Yup, my approach to normalizing to `Content-Type` makes it slower.

**Comment by jreinert** [comment]
@jhass: i like your approach too. What about:

``` ruby
def self.equals?(key1, key2)
  return false if key1.bytesize != key2.bytesize

  cstr1 = key1.to_unsafe
  cstr2 = key2.to_unsafe

  key1.bytesize.times do |i|
    next if cstr1[i] == cstr2[i]
    byte1 = normalize_byte(cstr1[i])
    byte2 = normalize_byte(cstr2[i])

    return false if byte1 != byte2
  end
end
```

should speed things up with really equal keys

**Comment by jhass** [comment]
Indeed, I updated the results and the patch.

**Comment by jreinert** [comment]
Further improvements in speed:

``` ruby
    private def self.normalize_byte(byte)
      char = byte.chr
      return byte if 'a' <= char <= 'z' || char == '-'

      if 'A' <= char <= 'Z'
        byte + 32
      elsif char == '_'
        '-'.ord
      else
        byte
      end
    end
```

This improves speed to the extent, that in the worst case:
`Fetch Content-Type from HTTP::Headers { "CONTENT_TYPE" => "bar" }`
HeadersCompare is 1.95x slower than HeadersPR

For the most common case:
`Fetch Content-Type from HTTP::Headers { "Content-Type" => "bar" }`
HeadersCompare is now almost on par with HeadersPR by being only 1.14x slower

**Comment by jreinert** [comment]
close in favor of #1459

**Pull request closed without merging**
