### PR TITLE
Int#to_s performance

### PR DESCRIPTION
**Pull request by yyyc514**
- if speed (and memory allocation) is the reason we're doing this seems
  we should do it for both 0 and 1

### CODE REVIEW

**Comment by yyyc514** [comment]
Before/after for base 2 optimized:

```
              user     system      total        real
Base 2    32.450000   3.350000   35.800000 (  34.023529)
Base 7    15.090000   2.880000   17.970000 (  16.152529)
hex       12.350000   2.870000   15.220000 (  13.392651)
base 17   11.710000   2.840000   14.550000 (  12.733819)
...
              user     system      total        real
Base 2    20.600000   3.260000   23.860000 (  21.796835)
Base 7    15.270000   2.750000   18.020000 (  16.272717)
hex       12.710000   2.760000   15.470000 (  13.699979)
base 17   11.670000   2.810000   14.480000 (  12.661558)
```

**Comment by yyyc514** [comment]
Optimize for base 16 also:

```
              user     system      total        real
Base 2    21.180000   3.290000   24.470000 (  22.538080)
Base 4    21.640000   3.140000   24.780000 (  23.057397)
Base 8    21.300000   3.180000   24.480000 (  22.657313)
Base 7    15.290000   2.840000   18.130000 (  16.347244)
hex       9.020000   2.070000   11.090000 (  9.850557)
base 17   11.840000   2.770000   14.610000 (  13.110471)
```

**Comment by yyyc514** [comment]
I think it makes sense that the base 16 and base 2 routes are the fastest.

**Comment by asterite** [comment]
@yyyc514 did you try these benchmarks with `--release`? For me it doesn't improve much. For base 16 it's like 4.52 vs 4.39.

**Comment by yyyc514** [comment]
What is `--release`?

**Comment by yyyc514** [comment]
``--release``:

Before:

```
              user     system      total        real
Base 2    12.200000   2.890000   15.090000 (  14.088559)
Base 4    7.390000   2.200000   9.590000 (  8.211301)
Base 8    5.870000   2.060000   7.930000 (  6.540725)
Base 7    6.210000   2.050000   8.260000 (  6.957524)
hex       5.300000   1.930000   7.230000 (  5.980135)
base 17   4.710000   2.070000   6.780000 (  5.475919)
```

After:

```
              user     system      total        real
Base 2    4.070000   2.210000   6.280000 (  5.019831)
Base 4    7.320000   2.120000   9.440000 (  8.103770)
Base 8    5.870000   2.090000   7.960000 (  6.588485)
Base 7    6.080000   2.080000   8.160000 (  6.812364)
hex       3.270000   1.980000   5.250000 (  3.955555)
base 17   4.740000   2.090000   6.830000 (  5.464223)
```

Significant difference here with Base 2 and Hex.

**Comment by yyyc514** [comment]
Late 2012 Macbook Pro Retina 2.5GHz here.

**Comment by yyyc514** [comment]
So we're comparing apples to apples:

```
require "benchmark"

# n = 1_000_000
n = 10_000_000
Benchmark.bm do |x|
   x.report("Base 2") do
    n.times do
     a = 99999999999.to_s(2)
    end
  end
   x.report("Base 4") do
    n.times do
     a = 99999999999.to_s(4)
    end
  end
   x.report("Base 8") do
    n.times do
     a = 99999999999.to_s(8)
    end
  end


   x.report("Base 7") do
    n.times do
     a = 99999999999.to_s(7)
    end
  end

  x.report("hex") do
   n.times do
  	 a = 99999999999.to_s(16)
   end
 end
  x.report("base 17") do
   n.times do
  	 a = 99999999999.to_s(17)
   end
 end
end

```

**Comment by yyyc514** [comment]
It's also measurably faster if we use the same algo for base 4 and 8, though I'm not sure who that helps:

```
              user     system      total        real
Base 2    3.860000   2.200000   6.060000 (  4.657184)
Base 4    3.480000   2.020000   5.500000 (  4.173317)
Base 8    3.210000   2.030000   5.240000 (  3.873808)
Base 7    6.120000   2.060000   8.180000 (  6.840408)
hex       3.310000   1.910000   5.220000 (  3.975483)
base 17   4.740000   2.070000   6.810000 (  5.466177)
```

**Comment by asterite** [comment]
You are right, I might have been doing something wrong.

By the way, did you run that same benchmark with Ruby? Ruby never stops to amaze me.

**Comment by yyyc514** [comment]
Ruby 2.0:

```
       user     system      total        real
Base 2  8.790000   0.120000   8.910000 (  8.977795)
Base 4  4.510000   0.020000   4.530000 (  4.576384)
Base 8  3.650000   0.060000   3.710000 (  3.828048)
Base 7  4.050000   0.080000   4.130000 (  4.291303)
hex  3.230000   0.030000   3.260000 (  3.353067)
```

Pretty crazy fast.  I wonder if it's just because it's calling sprintf or something other the hood to drop down to fast C code... I'm sure it's not running the algorithms itself like we've written them out.  If so that would really surprise me.

**Comment by yyyc514** [comment]
Wait, how can that be faster than Crystal?  `sprintf` vs our own logic?

**Comment by yyyc514** [comment]
Just out of curiosity:

```
hex             3.440000   1.980000   5.420000 (  4.089037)
hex (sprintf)   2.080000   0.610000   2.690000 (  2.300967)
```

**Comment by asterite** [comment]
It's not sprintf: https://github.com/ruby/ruby/blob/trunk/numeric.c#L2784-L2810

Basically, it doesn't allocate memory for the `StringIO`. I always like to optimize things, so I'll give this a try. There's also no need to reverse the buffer later.

**Comment by yyyc514** [comment]
And if I remove the temp buffer (for output) from the loop:

```
hex             3.240000   1.910000   5.150000 (  3.889440)
hex (sprintf)   1.270000   0.010000   1.280000 (  1.302723)
```

Now we're talking.  I tried removing the StringIO and replacing with StaticArray but had no luck... (though I wasn't trying --release at the time).

**Comment by yyyc514** [comment]
> It's not sprintf

Ha.  I think I forgot parts of the core lib are C, not Ruby.

**Comment by asterite** [comment]
Well, just for fun, I optimized it. Now it's slightly faster than Ruby if the base is not known at compile time. You can try this benchmark:

```crystal
require "benchmark"

TIMES = 2_000_000
Benchmark.bm do |x|
  2.upto(36) do |base|
    x.report("Base #{base}") do
      TIMES.times do
        a = 99999999999.to_s(base)
      end
    end
  end
  x.report("default") do
    TIMES.times do
      a = 99999999999.to_s
    end
  end
end
```

You can compare that directly to Ruby.

However, if you run your benchmark, the one that has several bases, in Crystal it runs much faster (make sure to set TIMES to 2_000_000). This is because LLVM knows the values at compile-time and can better optimize this. And since the base is like %99 known at compile-time, this is a win-win :-D

Things I had to do in order to optimize:

1. Use `UInt8[65]` as an temporary buffer and write there from back to front.
2. If we are writing to an IO, write that buffer to that IO. Otherwise (if it's just `#to_s`), we can create a String directly from the buffer with `String#new`. I found that `String.build` is slower because you have to allocate memory for the `String::Builder` class, and it can't be a struct (maybe with escape analysis this becomes irrelevant in the future).
3. I had to use `Int#reminader` instead of `Int#%` because the later is slower, which makes me wonder if changing `Int#%` for the maybe more correct but slower alternative was a good choice after all.
4. Use a string of all the digits and letters and index directly to that, like Ruby does.

The best thing is that the code actually ended up being simpler than before :-)

**Comment by asterite** [comment]
As a side note, this seems like a very small optimization... does it really matter that we can now convert numbers to strings in an arbitrary base really fast? Well, the thing is that that functionality is used in other places in the std and probably your code. For example, this:

```crystal
require "benchmark"
require "cgi"

TIMES = 2_000_000
Benchmark.bm do |x|
  x.report("escape") do
    TIMES.times do
      CGI.escape("this is a very long string !@#$%^&*()-_+=")
    end
  end
end
```

Before this last commit, it ran in 9.38 seconds. Now it runs in 1.2 seconds :-)

In Ruby it takes 23.24 seconds, at least on my machine.

**Comment by yyyc514** [comment]
Did you try your changes + my bit shifting to see if base % 2 could still be even crazy faster?

**Pull request merged**
