### PR TITLE
Allow for sending masked data from websocket.

### PR DESCRIPTION
**Pull request by kumpelblase2**
~~Quick note: Reason for WIP flag is because there is no spec yet.~~ Spec got added.

Purpose:

From a server perspective, this does not need to be there. However, when used from a client perspective, you are most (if not all) of the times required to mask your data. This PR allows sending data while requesting to send it masked to the receiver.

I have opted to not create a separate method for it as it basically does the same as the normal 'send' method.

Any feedback is appreciated :)

### CODE REVIEW

**Comment by dziulius** [comment]
Imho it would be better to have a separate method. See [this](http://www.rubydoc.info/github/troessner/reek/Reek/Smells/ControlParameter)

**Comment by kumpelblase2** [comment]
@dziulius does this seem better to you?

**Comment by asterite** [comment]
I preferred the boolean flag. It's something that you can forward from a method to another.

In any case, I'd like to review this with @waj

**Comment by dziulius** [comment]
I think it looks much nicer. But I'm unsure how crystal devs feel about practices from reek/rubocop in crystal.

**Comment by kumpelblase2** [comment]
Upon going through the RFC again, I've come to notice that a server MUST NOT send masked data while a client MUST send the data masked (RFC 6455, Section 5.1). Because of that, it might make more sense to create a subclass of the websocket specifically for a client websocket and just send all data masked every time.

Any thoughts?

**Comment by asterite** [comment]
@dziulius I think what you said, in this particular case, is right. If the client must send masked data and the server mustn't, then two different methods is the way to go. I'll check with @waj and we'll probably merge this (and later we'll change that array to a static array)

**Comment by asterite** [comment]
@kumpelblase2 I think having two methods is fine, simpler design :-)

**Comment by kumpelblase2** [comment]
which array are you talking about @asterite ?

**Comment by asterite** [comment]
@kumpelblase2 [this one](https://github.com/manastech/crystal/pull/1048/files#diff-60a943b677c4ea4d3b95b6e3429685e8R135). You can do [this instead](http://play.crystal-lang.org/#/r/97p). StaticArray is a struct so it lives on the stack, without allocating heap memory.

**Comment by kumpelblase2** [comment]
Ah I see, wasn't aware of that, but that certainly would make it better.

**Comment by kumpelblase2** [comment]
Alright sorry for the delay, I was on a long vacation.
Apart from the static array (which I added just now) is there anything missing?

**Pull request merged**
