### PR TITLE
[HTTP::Params] Add #to_h returning internal hash

### PR DESCRIPTION
**Pull request by waterlink**
Followup for #1569 related to this and following comments: https://github.com/manastech/crystal/pull/1569#issuecomment-144097167

### CODE REVIEW

**Comment by jhass** [comment]
Shouldn't it return a copy? modifications being reflected in the original, idk.

**Comment by asterite** [comment]
I think a copy is overkill. If you want to parse the params as a raw hash you don't have an efficient way, so doing `HTTP::Params.parse(...).to_h` sound reasonable IMO.

**Comment by waterlink** [comment]
On the other hand it can lead to very confusing results if someone will use both wrapper and internal hash in different parts of the program.

**Comment by asterite** [comment]
That's why the original `parse` method returned a Hash. If you wanted a wrapper, you could use it explictly (of course, the wrapper didn't exist until your PR). This way is more convenient but then you have to start thinking how to "unrwap" the wrapped value. Or we can add a `parse_hash`, I don't know. I think we should favor composable things.

Or we can just remove the `to_h` method and see what happens.

**Comment by asterite** [comment]
Don't worry, it was my suggestion to add `to_h` but we still don't know if that's going to be useful, probably the wrapper is good enough. You can close this if you want :-)

**Comment by waterlink** [comment]
So I see now these paths to go forward:

- add `to_h` with copying (no mutation bugs, maybe slight performance problem),
- add `to_h` without copying (no performance impact, maybe some confusing mutation bugs),
- not add `to_h`, therefore force developer to use this wrapper (no impact and no confusion, but wrapper can have less capabilities than original hash - in that case developer can create a PR to stdlib I suppose),
- add `parse_hash` (no impact, choice to developer if he wants to use raw hash or wrapper),
- make `parse` return `Hash(String, Array(String))` (leave choice to developer to use wrapper or not explicitly with `HTTP::Params.new(hash)`).

**Comment by waterlink** [comment]
Yeah, I think option with closing this PR for now, and see what happens afterwards is quite interesting :)

**Comment by waterlink** [comment]
So, closing for now.

**Pull request closed without merging**
