### PR TITLE
Basic documentation for crystal's spec standard library

### PR DESCRIPTION
**Pull request by PragTob**
Hi everyone,

first of thanks for your work and dedication going into crystal. It's a fascinating language and the fact that it is implemented in itself is sort of a "ruby implemented in ruby" dream come true to me. Reading code is extremely fun :)

Anyway, this is my first stab at a basic documentation for the high level standard library spec documentation. Without a REPL tests are my way to learn the language so I think this is extremely important :)

Comments about style/grammar/other important things to include extremely welcome!

Tobi

PS: I believe that testing is important enough that spec should make it into the crystal docs not just the stdlib but that's for another day :)

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Grammar nerd coming through! A few suggestions:

- The word `crystal` in the first line should be capitalized.

- A *lot* of sentences here begin with a noun. How about changing it up a little? For instance, changing:

```
Specs live in the `spec` directory of a project by convention.
```

to

```
By convention, specs live in the `spec` directory of a project.
```

- `You can` is used a lot. You can (!) change the second one to just `Also,` and the third occurrence to `In addition,`.

- Here:

```
You can also just compile and run individual files by providing a path to a spec file.
```

you're referencing the spec file twice. How about (with the fix I mentioned above):

```
Also, you can compile and run individual spec files by providing their path:
```

Just a few ideas. ;)

**Comment by PragTob** [comment]
Thanks, suggestions sound much better. Can't believe I started 3 sentences with "You can" :blush:

**Comment by PragTob** [comment]
Hey anything I should still adjust here? Would love to get a bit of `spec` documentation into crystal and maybe some more :)

**Comment by asterite** [comment]
@PragTob Thanks! I'll merge it soon, probably tomorrow.

Would you mind if I remove the reference to Ruby? I don't want to assume Ruby knowledge from users, even if it's just a reference. I'll also probably add a bit more documentation saying how to structure tests, what's the difference between `describe` and `it`, etc.

**Comment by PragTob** [comment]
Hey Ary! :)

I don't mind at all, your project your rules. As crystal itself is sort of promoted as being close to the ruby language in spirit I just thought it might make sense to reference rspec, so that rubyists might feel at home right away.

I'll remove the ruby reference and put in a bit more about `describe`/`it` - you are right that was missing, worked with rspec for too long so it feels too natural :D

**Comment by PragTob** [comment]
Hey,

I removed the reference to ruby and added further docs for describe/it/should on a basic/introductory level. Hope you like'em but feel free to change them up as you see fit! :)

Tobi

**Comment by asterite** [comment]
@PragTob Thanks!

**Pull request merged**
