### PR TITLE
Added Enumerable#each_slice

### PR DESCRIPTION
**Pull request by havenwood**

### CODE REVIEW

**Comment by ysbaddaden** [comment]
Thx! I did the same recently (I love this method) but it was postponed because it should return an enumerable, not an array, which crystal doesn't yet support —but would be incredible to.

**Comment by ysbaddaden** [comment]
Scratch that, you actually invoke a block.

**Comment by asterite** [comment]
Thanks!!

Some notes before we accept this:

1. In Ruby `Enumerable#each_slice` returns `nil`. I think creating the Array(Array(T)) is unnecessary and will slow down things, so I would return `nil` too.
2. Instead of cloning the slice, I would create a new slice each time a new one is needed. Otherwise you end up creating an extra unnecessary copy of the array.
3. I [just documented](https://github.com/manastech/crystal/commit/c349cce6ad8b790a60287f50fab20db73216539f) the difference between `dup` and `clone`. We won't be using neither of these here because of point 2, but `dup` would have been more appropriate, otherwise you end up creating deep copies of the enumerable's values.

**Comment by asterite** [comment]
Sorry for the delay, just now I see you made those changes. Thanks!

**Comment by asterite** [comment]
I added this [here](https://github.com/manastech/crystal/commit/d695c37e72c6f6b0adc4c44f2fabd5ec307c51e4). Sorry, automatic merge wasn't possible and I'm not very good with git :cry: (I tried but it became a mess so I reset it)

**Pull request closed without merging**
