### PR TITLE
Optimize Array.shift

### PR DESCRIPTION
**Pull request by kirbyfan64**
Ref. #573.

### CODE REVIEW

**Comment by PragTob** [comment]
For things like this I always like to see benchmarks and potentially even adding them to the project so they can be rechecked :)

**Comment by kirbyfan64** [comment]
x = Array(Int32).new 9999999, 0
    x.shift(9999)
    x.shift(9999)
    x.shift(9999)
    x.shift(9999)
    puts x[2] # make sure this won't get optimized out

You might want to try more calls to `shift`; my laptop started acting wonky. :(

**Comment by asterite** [comment]
I tried this benchmark:

```crystal
x = Array(Int32).new 99999999, 0
time = Time.now
20.times do
  x.shift(9999)
  x.shift(9999)
  x.shift(9999)
  x.shift(9999)
end
puts Time.now - time
```

I tried this both with `--release` and without it. I couldn't find any difference in performance. And since the original code is shorter, I prefer that one.

@kirbyfan64 Can you confirm the same result in your machine?

**Comment by kirbyfan64** [comment]
@asterite Try this:

```crystal
time = Time.now
x = Array(Int32).new 9999999, 0
20.times do
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
  x.shift 9999
end
puts Time.now - time
```

I sort of unrolled the loop. Building in release mode, this version is, on average, about 0.1-0.2s faster than the current one, although the time taken fluctuates a bit more (probably due to glibc's memcpy prefetching).

**Comment by funny-falcon** [comment]
If Array#shift is a really critical, then it has a sense to add `offset` field to array:
````ruby
class Array
    getter length
    @length :: Int32
    @offset :: Int32
    @capacity :: Int32
    def shift
    if @length == 0
      yield
    else
      value = @buffer[@offset]
      (@buffer + @offset).clear
      @length -= 1
      @offset += 1
      value
    end
  end

  def shift(n)
    if n < 0
      raise ArgumentError.new("can't shift negative count")
    end

    n = Math.min(n, @length)
    ary = Array(T).new(n)
    ary.length = n
    ary.buffer.move_from(@buffer+@offset, n)
    (@buffer + @offset).clear(n)
    @length -= n
    @offset += n
    ary
  end
````
But that means, that all access to `@buffer` should be made with `@offset`

**Comment by ozra** [comment]
Or simply increase the front-pointer, reduce length, increase shifted_count and do chunked ditches of the out shifted data at what-not intervals in relation to the total size.

**Comment by kirbyfan64** [comment]
@ozra But then won't the memory usage get too high?

**Comment by asterite** [comment]
@ozra The problem is that when the array needs to grow we do `realloc`, but `realloc` must receive the original pointer you used for `malloc`, so we can't forget that initial pointer. An alternative would be to do what @funny-falcon says, but that will probably make all other array operations slower (maybe, we'd have to benchmark) and make each array 4 bytes bigger.

**Comment by ozra** [comment]
@ozra - a threshold for when to do the moves based on the array size would be sufficient. I assume re-allocation works in a similar way (haven't looked at the code): pre-allocating some extra space at pushes. So, same thing in the other direction so to speak.
@asterite, that's why the "shifted_count" is maintained. Needed for the chunked moves anyway. So at re-allocation time, same thing: use (front - shifted_count).

Do pointer arithmetic at alloc/move, not on every access...

**Comment by funny-falcon** [comment]
@ozra is right: it is possible to maintain shift count and move front pointer:

````ruby
class Array
  getter length
  @length :: Int32
  @shifted :: Int32
  @capacity :: Int32
  def shift
    if @length == 0
      yield
    else
      value = @buffer[0]
      @buffer.clear
      @length -= 1
      @shifted += 1
      @buffer += 1
      value
    end
  end

  def shift(n)
    if n < 0
      raise ArgumentError.new("can't shift negative count")
    end

    n = Math.min(n, @length)
    ary = Array(T).new(n)
    ary.length = n
    ary.buffer.move_from(@buffer, n)
    @buffer.clear(n)
    @length -= n
    @shifted += n
    @buffer += n
    ary
  end
  private def resize_to_capacity(capacity)
    if @capacity + @shifted >= capacity
      @buffer -= @shifted
      @buffer.move_from(@buffer + @shifted, @length)
      @capacity += @shifted
    else
      @capacity = capacity
      @buffer = @buffer.realloc(@capacity)
    end
  end
````

**Comment by funny-falcon** [comment]
Another alternative is mainain two pointers:
@buffer points to first element,
@base_buffer points to allocated place

**Comment by funny-falcon** [comment]
Oh, sorry, resize_to_capacity is wrong in `else` case

**Comment by asterite** [comment]
I did several benchmarks with `Benchmark.ips` and didn't notice a big difference between the two `shift` versions: sometimes the current one wins, sometimes the new one wins, but by 1.02x, which isn't significative.

I also don't think we should keep an index into the buffer, because repetitive pop/shift operations would end with a huge buffer that points to a few elements. So for now I'll close this. @kirbyfan64 Thanks anyway for trying to optimize things! :-)

**Comment by funny-falcon** [comment]
> I also don't think we should keep an index into the buffer, because repetitive pop/shift operations would end with a huge buffer that points to a few elements
buffer will be 

But current `shift` does the same when called without arguments.

Did you test this:
````ruby
x = Array(Int32).new 9999999, 0
9999.times do
  20.times do
    x.shift
  end
  20.times do
    x.push 0
  end
end
````
I'll prepare pool request, if you'll give it a chance.

**Comment by asterite** [comment]
@funny-falcon Note that the method changed by @kirbyfan64 is `shift(n)`, not the regular shift.

I tried this:

```crystal
require "benchmark"

ary = Array(Int32).new 9999999, 0

Benchmark.ips do |x|
  x.report("shift") do
    ary2 = ary.dup
    50.times do
      20.times do
        ary2.shift(10)
      end
      20.times do
        ary2.push 0
      end
    end
  end
  x.report("shift2") do
    ary2 = ary.dup
    50.times do
      20.times do
        ary2.shift2(10)
      end
      20.times do
        ary2.push 0
      end
    end
  end
end
```

where `shift2` is the alternative implementation. My result is:

```
 shift     0.23 (±  0.00)       fastest
shift2     0.22 (±  0.00)  1.04× slower
```

I run it again:

```
 shift     0.24 (±  0.00)  1.01× slower
shift2     0.24 (±  0.00)       fastest
```

So I don't think there's a real difference.

**Pull request closed without merging**
