### PR TITLE
[ci skip] Update command.cr

### PR DESCRIPTION
**Pull request by sdogruyol**

### CODE REVIEW

**Comment by jhass** [comment]
Well, make the capitalization of Crystal consistent too then?

**Comment by asterite** [comment]
I think the `Crystal` there is redundant

**Comment by jhass** [comment]
Then it probably should go from `init` too.

**Comment by sdogruyol** [comment]
Got it :+1:

**Comment by sdogruyol** [comment]
Done

**Comment by jhass** [comment]
Thanks, a slightly more informative commit message would be great in the future ;)

**Comment by sdogruyol** [comment]
Thanks @jhass i'll keep that in mind :+1:

**Pull request merged**
