### PR TITLE
Extend license to 2015 and convert to Markdown

### PR DESCRIPTION
**Pull request by maclover7**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Is there a reason for this? I rarely ever see Markdown-formatted licensesm

**Comment by ysbaddaden** [comment]
Yes, licences are usually used verbatim as plain text.

**Comment by asterite** [comment]
Please leave it as text/plain and just change the year. Thanks!

**Comment by TheLonelyGhost** [comment]
NOTE: the year should be updated again to 2016.

**Comment by maclover7** [comment]
Looks like this isn't needed anymore.

**Pull request closed without merging**
