### PR TITLE
Improve building from source instructions

### PR DESCRIPTION
**Pull request by yyyc514**

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! But I don't want to make the `Contributing` file too big because maybe it makes it more tedious to read and encourages less contribution.

I recently updated the `Contributing.md` file to reference a list of dependencies. It also says that you need LLVM, so I think that's enough for now.

**Comment by asterite** [comment]
(I'm doing a pull-requests/issues cleanup, the number is starting to get higher)

**Comment by yyyc514** [comment]
Is there harm in putting better directions in a separate file then if they don't belong here?

**Comment by asterite** [comment]
@yyyc514 Not at all, if you want we can create a Wiki page for that.

**Pull request closed without merging**
