### PR TITLE
Update Projectfile and .travis.yml templates

### PR DESCRIPTION
**Pull request by will**
Once https://github.com/travis-ci/travis-build/pull/465 lands, slated for 2015-06-29

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! (And also big thanks for making travis support possible)

There are some failing specs. But don't worry, I can merge this after travis support lands and fix it.

**Comment by will** [comment]
The specs were easy enough to fix so I re-pushed with the specs. I didn't think there'd be specs for that so didn't run them :)

**Comment by waterlink** [comment]
Looks good to me.

Travis fails on linux because of gnupg keys being expired I think. So they might need to be renewed.

**Comment by asterite** [comment]
Thanks!

**Pull request merged**
