### PR TITLE
add Benchmark.ips

### PR DESCRIPTION
**Pull request by will**
### Measure the number of iterations per second of each task

``` crystal
require "benchmark"
Benchmark.ips do |x|
  x.report("short sleep")   { sleep 0.01  }
  x.report("shorter sleep") { sleep 0.001 }
end
```

This generates the following output:

```text
  short sleep    91.82 (±  1.11)  8.72× slower
shorter sleep   800.98 (±  4.72)       fastest
```

`Benchmark::IPS` defaults to 2 seconds of warmup time and 5 seconds of
calculation time. This can be configured:

``` crystal
Benchmark.ips(warmup: 4, calculation: 10) do |x|
  # …
end
```

### CODE REVIEW

**Comment by jhass** [comment]
Awesome! Thank you!

**Comment by asterite** [comment]
@will I wanted to have this for a long time, thank you!!

It's so boring to have `N = 1000`, run the benchmark, mmm... no, I need a bigger N, times are too small. Nope, still bigger. `Benchmark.ips` is the zen of benchmarking.

Should we have some text after the numbers? I guess "91.82 (±  1.11)" are iterations per second, but maybe being explicit is better.

**Comment by asterite** [comment]
@will Forgot to say: thank you also for adding documentation for this! I also like that you put it before the `Benchmark.bm` method, I agree that `ips` is the most convenient one.

**Comment by will** [comment]
> Should we have some text after the numbers? I guess "91.82 (± 1.11)" are iterations per second, but maybe being explicit is better.

I think text after every one would be too much repetition. A header might be a good compromise though.

**Pull request merged**
