### PR TITLE
delegate macro supports multiple methods

### PR DESCRIPTION
**Pull request by elthariel**
The title is pretty explicit i guess.

I think we can save some typing by allowing to delegate multiple methods to the same object in one call.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Yeah this would be time-saving :+1:

**Comment by omninonsense** [comment]
This seem like it would be convenient! A :+1: from me, too.

**Comment by sdogruyol** [comment]
This would be a perfect fit for https://github.com/sdogruyol/kemal/blob/master/src/kemal/context.cr#L26-L28

**Comment by asterite** [comment]
Looks good! :-)

I think it works too if you do `macro delegate(*names, to_object)`. In any case the macro just became "arg-unsafe": I can do `delegate :foo` and I won't get any compile error and that line won't do anything. So maybe doing something like: `macro delegate(first_name, *other_names, to_object)` so we make sure you at least call it with two arguments. Or just `{{ raise "..." if names.size < 1 }}` for the `delegate(*names, to_object)` variant.

**Comment by elthariel** [comment]
Thanks for the tip :+1: ! Update on the way

**Comment by asterite** [comment]
Thanks!!

**Comment by elthariel** [comment]
Yeah, my first crystal contribution !

**Pull request merged**
