### PR TITLE
Add returned type restrictions to methods in Random

### PR DESCRIPTION
**Pull request by adlerhsieh**

### CODE REVIEW

**Comment by jhass** [comment]
Why not the specific ones?

**Comment by adlerhsieh** [comment]
Do you mean like `Int32` instead of `Int`?

**Comment by jhass** [comment]
Yes

**Comment by waj** [comment]
Why do we need these?

**Comment by adlerhsieh** [comment]
Updated. @waj It's for both documentation and the compiler, as mentioned in #1657.

**Comment by ysbaddaden** [comment]
IMHO `crystal docs` should do that itself. Let's remember one motive of Crystal: not having to declare types.

**Comment by adlerhsieh** [comment]
I think the returned types are part of the 'crystal docs' that users can see what these methods return right in the method summary, without the effort of trying them out.

**Comment by adlerhsieh** [comment]
Or maybe later I'll add some documentation to these methods to make it more complete, rather than making it look like the type declarations are necessary.

**Comment by asterite** [comment]
@ysbaddaden The compiler can't infer return types without actually having code that invokes those methods.

I personally don't put return types, and almost never use type restrictions unless it's for overload purposes, but it's nice to have them for documentation purposes, and as an added bonus the compiler will check those (on instantiation).

**Comment by jhass** [comment]
@asterite I take this as a "let's accept this". Please just make use of the big green button if you want to accept something that has little friction and a passed build. We can always easily revert a merge if turns out bad for some reason.

**Comment by adlerhsieh** [comment]
@asterite Thanks for clarification!

**Pull request merged**
