### PR TITLE
Added Enumerable#each_cons

### PR DESCRIPTION
**Pull request by havenwood**

### CODE REVIEW

**Comment by jhass** [comment]
I wonder if we can have a version that uses `#[]` if available, but also works without. This version basically only works with Arrays, not even Hashes, right?

**Comment by Exilor** [comment]
What @jhass said. I'd have a more universal version for Enumerable and a faster one for Array:
```ruby
module Enumerable(T)
  def each_cons(count : Int)
    each_with_index do |elem, index|
      cons = Array(T).new(count)
      each_with_index do |e, i|
        cons << e if i >= index && cons.size < count
      end
      cons.size < count ? break : yield cons
    end
    nil
  end
end

class Array(T)
  def each_cons(count : Int)
    each_index do |i|
      i + count > length ? break : yield self[i, count]
    end
    nil
  end
end
```
Methods in Enumerable should only require the class where it is included to implement ```#each```.

**Comment by jhass** [comment]
I think we can keep the current version but operate on the result of `.to_a`, given the diversity of structures that Enumerable is and might be included in, some of them might be able to provide a efficient to_a and thus would benefit from the efficient `.each_cons`.

**Comment by asterite** [comment]
As @jhass says, Enumerable should only use `each` and other Enumerable methods, never assume it will be an array. But I wouldn't invoke `to_a`: an Enumerable can be never-ending!

@Exilor's version is almost correct, but it reuses the yielded Array. A new Array must be created for each yielded value. Try it in Ruby:

```ruby
[1, 2, 3, 4].each_cons(2) do |x|
  puts x.object_id
end 
```

This method, `each_slice`, and probably other methods, make me only be able to imagine the terrible performance of these methods.

Real question: I never used `each_cons` in my life, what's a use case for it?

I can imagine these methods being used in small collections, and documentation should say their performance is awful and that they shouldn't be used for big collections. Which make me wonder if we really want to have these methods in the standard library.

**Comment by havenwood** [comment]
Oops, yeah I hadn't thought this one through! Exilor's Enumerable version makes sense.

I don't think #each_cons is as useful as #each_slice or even #chunk.

It seems the most common use case is #each_cons(2) for pairs of consecutive elements. Or [Project Euler #47](https://projecteuler.net/problem=47) is a somewhat contrived example in Ruby of using other slice sizes:

```ruby
require 'mathn'

def smallest_consecutive_prime_factors size
  1.upto(Float::INFINITY).each_cons(size).find do |consecutive|
    consecutive.all? { |n| n.prime_division.size == size }
  end
end

smallest_consecutive_prime_factors(4)
#=> [134043, 134044, 134045, 134046]
```

**Comment by havenwood** [comment]
Closing since my implementation totally missed the mark.

**Comment by Exilor** [comment]
@asterite 

```ruby```
[1, 2, 3, 4].each_cons(2) do |x|
  puts x.object_id
end 
```
Ruby:
```ruby
70007792192660
70007792192560
70007792192500
```
Crystal:
```ruby
25202496
25202464
25202432
```
I don't see the difference :/
This method and ```#each_slice``` allocate arrays like crazy, yes, but if what they do can't be accomplished in a better way then what else can be done?
I've noticed there are many methods from Ruby that you don't see the point of. Perhaps you'd like to keep these "ruby compatibility" methods in a different file that can be required if needed?

**Pull request closed without merging**
