### PR TITLE
[ci skip] Fix returned type of `Def#body`

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! You really pay attention to details :-)

I saw that you recently contributed 100 commits to rails, congratulations!

**Comment by yui-knk** [comment]
@asterite Thank you for blessing:)  BTW can we release crystal 0.7.5 ??

**Comment by asterite** [comment]
Yes, I was thinking the same, many additions and bug fixes since 0.7.4. I'll try tomorrow :)

**Comment by yui-knk** [comment]
thanks :yellow_heart: 
I can't wait for 0.7.5 :)

**Pull request merged**
