### PR TITLE
move byte_format to std/ for getting bytes of numbers without io

### PR DESCRIPTION
**Pull request by jreinert**
if this is fine by you then i'll need to update #1603

### CODE REVIEW

**Comment by jreinert** [comment]
@asterite: @jhass pointed out that this won't be zero-copy anymore because i'm returning a stack value. Would a `@[AlwaysInline]` go around this?

**Comment by asterite** [comment]
There's no performance penalty, LLVM optimizes this very well.

Even though I like this (though I don't know in which scenario you would need raw bytes if not for sending that through an IO), how would the `decode` part work?

**Comment by jreinert** [comment]
@asterite a few cases where i've needed this:

``` crystal
size_bytes = size.bytes(ByteFormat::NetworkEndian)
size_bytes[0] |= 0x80 if masked?
io.write(size_bytes.to_slice)

key_bytes = mask_key.bytes(ByteFormat::NetworkEndian)
io.write(key_bytes.to_slice)

size.times do |i|
  io.write_byte(payload.read_byte.not_nil! ^ key_bytes[i % 4]
end
```

for the decode part i can't think of a way it should work with anything else than an io. *maybe* an overload with `Slice(UInt8)`.

**Comment by asterite** [comment]
I kind of like turning a number into bytes that easily (just 1.bytes), but the ByteFormat module will have kind of different methods, one with IO, the other one without it, so we are not sure about this yet. We'll review it later and give you feedback.

**Comment by asterite** [comment]
We think byte format is related to IO, and instead of converting numbers to bytes you should write them directly to an IO.

**Pull request closed without merging**
