### PR TITLE
Fix SDL Samples

### PR DESCRIPTION
**Pull request by weskinner**
I was receiving this compiler error when running the SDL samples:

```
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function _start': (.text+0x20): undefined reference to 'main'
```

### CODE REVIEW

**Comment by asterite** [comment]
Thanks!

I think this fixes it for linux but breaks it for mac :-)

I'll merge but fit it by using `ifdef`.

**Comment by asterite** [comment]
There: df182ad8d25af388b0102a9895615d8f2ac8f960.

But let me know if it broke again in linux :-)

**Comment by weskinner** [comment]
works!  However, I don't understand why I am having to build with link flags for the linker to see SDL:

` william@ubuntu:~/crystal$ ./bin/crystal build --link-flags -lSDL samples/sdl/fire.cr `

**Comment by weskinner** [comment]
credit goes to @ysbaddaden for this fix

**Pull request merged**
