### PR TITLE
Add flat method for arrays

### PR DESCRIPTION
**Pull request by jalyna**
I set up a really simple `Array#flat` method. I'm not sure yet if this is the way to go. I would be very happy if I could get some feedback about it. Thank you!

(Btw. I'm a little bit confused by the array notation in the specs and the docs as we sometimes use spaces like `[ 3, 4 ]` and `[3, 4]`)

### CODE REVIEW

**Comment by yui-knk** [comment]
:)

I think

* how about to support over level 3 array?

```
[1, [1, 2, [3]]].flat
#=> [1, 1, 2, 3]
```

* how about to add `level` agrs to this method?

```
[1, [1, 2, [3]]].flat(1)
# => [1, 1, 2, [3]]
```

this is better :yellow_heart: 

* how about method name to `flatten`?

Sure crystal is not Ruby, so it is not matter they do not have same name. Why do you name this method to `flat` ?

**Comment by jalyna** [comment]
@yui-knk Yepp I was struggling with this as I think this is not possible in static typed languages. I looked a little bit around in java & scala (e.g. [flatten in scala](https://www.safaribooksonline.com/library/view/scala-cookbook/9781449340292/ch10s16.html)) to proof this. I also talked with some developers and I think it is quite unusual (or they even called it "being lazy") to do it more than once.

But if you have an idea how I could do it I would be super super happy. 

Also because of this reason there can be no `flat!` method because then the type has to change...

**Comment by jhass** [comment]
Also see #1009

**Comment by yui-knk** [comment]
@jalyna  at least

```crystal
  def flat
    ary = [] of T
    each do |e|
      if e.is_a?(Array)
        e.flat.each do |e2|
          ary << e2
        end
      else
        ary << e
      end
    end
    ary
  end
```

passed (I feel `#concat` maybe suspicious)

```crystal
    it "flats a level 3 array" do
      [[1, 2], 5, [3, [4]]].flat.should eq([1, 2, 5, 3, 4])
    end
```

But I found out that these tests not pass :cry: 

```crystal
    it "flats a level 2 array" do
      [[1, 2], [3, 4]].flat.should eq([1, 2, 3, 4])
    end

    it "flats also mixed arrays" do
      [[1, 2], ["a", "b"]].flat.should eq([1, 2, "a", "b"])
    end
```

**Comment by yui-knk** [comment]
Someone know how to get type from array ?

```
some_method([1, 2])
# => Int32

some_method([1, "a"])
# => [Int32, String]
```

**Comment by Exilor** [comment]
@yui-knk http://play.crystal-lang.org/#/r/9gc ?

**Comment by yui-knk** [comment]
@Exilor thanks!

**Pull request closed without merging**
