### PR TITLE
Crypto::Blowfish

### PR DESCRIPTION
**Pull request by akaufmann**
Hi guys!

I have implemented Crypto::Blowfish. It has not all features right now (encrypt / decrypt of blocks are missing).
But all features for Bcrypt are there (Blowfish#salted_expand_key). If you are interested in Bcrypt for the std crypto lib as well, let me know :-)

I also modified Crypto::MD5 to have the same structure as Blowfish. Hope this is okay for you.

### CODE REVIEW

**Comment by Exilor** [comment]
Just out of curiosity. Why do you need all those "% ULONG" for?

**Comment by akaufmann** [comment]
It verifies that the correct bits are set/unset. This is the hexadecimal notation for 4294967296, i.e. the number of different values a 32-bit integer can have. As long as it is a 32-bit integer it is not necessary. But I go on the safe side and I saw it in Ruby's Blowfish.

**Comment by ysbaddaden** [comment]
Crystal uses 32-bits integers if they're initialized as such `1_i32` or `1_u32` —I think 32 bits is the default but better be safe with crypto—, so the modulo could be replaced for proper types.

**Comment by asterite** [comment]
Thanks for this! We'll review it soon.

Quick question: why the union of `Int32 | Int64`? Is it because you didn't know about the `_i64` suffix for numbers?

**Comment by akaufmann** [comment]
I know it. I used the union only because I must convert every number to Int64 and I thought the performance would not as good as I wish. But if it is the opposite or a better style for you, I can change it.

**Comment by asterite** [comment]
I think the performance will be better if there are no unions, as every operation on a union involves a dispatch. In this case a dispatch is just "if it's Int32, do this, otherwise (Int64) do this other thing". And that is probably slower than just using Int64.

But I guess it's tedious to mark every number in those big arrays and matrixes with Int64. Maybe, because we also needed it a couple of times, in the future you will be able to do:

```crystal
[1, 2, 3] of Int64
```

and the compiler won't complain and treat it as if you would have written:

```crystal
[1_i64, 2_i64, 3_i64] of Int64
```

So it's less tedious to write and the type of every number there can be changed with a single change.

Let me check with @waj, I think we can merge it like this. We can always improve the performance later :-)

**Comment by Exilor** [comment]
@asterite 
Wouldn't this be simpler than changing the compiler?
```ruby
struct Number
  def self.[](num, *nums)
    array = Array(self).new(1 + nums.length) << cast(num)
    nums.each { |n| array << cast(n) }
    array
  end
end
```
and you could simply write ```Int64[1, 2, 3]```.

**Comment by jhass** [comment]
Simpler yes, and could be a single line with `Array(self).new(items.size) {|i| cast(items[i]) }`, but it would be a run-time conversion instead of a compile-time one.

**Comment by asterite** [comment]
@Exilor: Genius!

I hadn't thought of that. Well, actually, in the early days we thought about having `T[...]` be the syntax for array creation, but that would make it impossible to have customized `#[]` methods for classes, so we quickly dropped that idea. But I think  that for `Number` it makes sense and it can indeed be very useful and convenient.

@jhass: LLVM is very smart, those casts end up being just a [zext](http://llvm.org/docs/LangRef.html#zext-to-instruction) or [trunc](http://llvm.org/docs/LangRef.html#trunc-to-instruction) operations. In release mode the `cast` method will be gone and the values will be stored directly in the array with the correct type.

I just tried this program, using @Exilor's code:

```crystal
fun foo : Int64
  x = Int64[1, 2, 3]
  x[0]
end

foo
```

And for `foo`'s llvm code I get lines like this:

```llvm
store i64 1, i64* %7, align 8
%.idx1.val.i = load i64** %9, align 8
%10 = getelementptr inbounds i64* %.idx1.val.i, i64 1
store i64 2, i64* %10, align 8
%.idx.val.i = load i64** %9, align 8
%11 = getelementptr inbounds i64* %.idx.val.i, i64 2
store i64 3, i64* %11, align 8
```

You can see that LLVM just stores i64, no cast.

I always trust LLVM a lot, and many times it surprises me :-)

I think we could add `Number::[]` to the standard library. @Exilor I would make it so that you can also write `Intt64[]` if you want, to initialize it to an empty array. Or why did you put a required argument?

**Comment by Exilor** [comment]
Actually the method that I use on my projects has two overloads, the one I wrote before and one without args:

```ruby
struct Number
  def self.[](num, *nums)
    array = Array(self).new(1 + nums.length) << cast(num)
    nums.each { |n| array << cast(n) }
    array
  end

  def self.[]
    [] of self
  end
end
```
Coincidentally I wrote it because I was also doing some Blowfish stuff (translated from Java).

**Comment by asterite** [comment]
I'll accept it as it is right now. We can always optimize it later if we want :smiley:

**Comment by asterite** [comment]
@akaufmann  And if you want to do BCrypt, please do so! We think standard, frozen algorithms should belong to the standard library so they are not replicated in many libraries, and we can always improve them and optimize them so everyone gets those benefits.

**Comment by asterite** [comment]
@akaufmann Quick question: salted_expand_key seems not to be used. Can I remove it?

**Comment by asterite** [comment]
@akaufmann Another one: if the argless `initialize` method useful? Because the one with the `key` argument checks it must be between 1 and 56 bytes, so I guess an empty key doesn't make sense. By the way, I checked this with Ruby's Crypt::Blowfish and their constructor also requires a key.

**Comment by asterite** [comment]
By the way, I ran a benchmark against https://rubygems.org/gems/crypt

This is crystal:

```crystal
require "crypto/blowfish"

a = 0_i64
(1..56).each do |i|
  bf = Crypto::Blowfish.new("a" * i)
  orig_l, orig_r = 0xfedcba98, 0x76543210

  l, r = bf.encrypt_pair(orig_l, orig_r)

  a += l
  a += r

  l, r = bf.decrypt_pair(l, r)

  a += l
  a += r
end

puts a
```

This is Ruby 2.1.4:

```ruby
require "crypt/blowfish"

a = 0
(1..56).each do |i|
  bf = Crypt::Blowfish.new("a" * i)
  orig_l, orig_r = 0xfedcba98, 0x76543210

  l, r = bf.encrypt_pair(orig_l, orig_r)

  a += l
  a += r

  l, r = bf.decrypt_pair(l, r)

  a += l
  a += r
end

puts a
```
Both print 629910082368 at the end, so I guess your implementation works ok :-)

The times:

```
Ruby: 1.097s
Crystal: 0.049s
```

22 times faster :-)

Then I optimized a little bit your version: I removed that `Int32 | Int64` union, and I also removed some Pointer.malloc (soon I'll commit the code so you can see the changes). With these changes Crystal takes 0.029s to execute that, which makes it 38 times faster.

The point to take from this, I guess, is that even if you don't pay that much attention to types (like, introducing a union by mistake), the times will be quite good. Yay! :-)

**Comment by akaufmann** [comment]
@asterite Great! :blush: 

To answer your questions.
For Bcrypt. We don't need to initialize a new Blowfish instance with a key. Secondly, we must fold the salt during the key schedule not just a key expansion.

```crystal
sl = Base64.decode64(salt) # Bcrypt needs his own Base64. Note that this is *not* compatible with the standard MIME-base64 encoding.
bf = Blowfish.new
bf.salted_expand_key(sl, key)
```
This is implemented very similar in Rust's and Go's Blowfish (of course, Rust and Go has no constructors).

https://github.com/DaGenix/rust-crypto/blob/master/src/blowfish.rs#L245
https://github.com/golang/crypto/blob/731db29863ea7213d9556d0170afb38987f401d4/blowfish/block.go#L71

But of course, if you have some good ideas to use only Blowfish#expand_key and initializer(key), let us know!

**Comment by akaufmann** [comment]
BTW, if I have some questions about the language, where can I reach you or other experienced user?  On the IRC channel?

**Comment by asterite** [comment]
There, I just pushed a commit.

Could you write a spec or two for the empty constructor case and `salted_expand_key`? That's why I thought they were not used, because when I deleted them the specs still passed.

For experienced users I doubt you will find someone who has more than 2 years of experience in the language :wink: 

Joke aside, you can find us on IRC, but now always. I think I also like it if you create GitHub issues with the label "question". GitHub is very comfortable for replying, since you can write in markdown, include code snippet, etc. Plus others can later search for issues and find questions and answers that might help them.

**Comment by akaufmann** [comment]
> For experienced users I doubt you will find someone who has more than 2 years of experience in the language

More than I have, at least in Crystal :wink:

> Could you write a spec or two for the empty constructor case and salted_expand_key?

Yep, they are coming ...

>  I think I also like it if you create GitHub issues with the label "question".

:+1:

**Comment by vendethiel** [comment]
> think I also like it if you create GitHub issues with the label "question".

You can't add tags to questions if you're not collaborator / owner

**Comment by asterite** [comment]
@vendethiel Right... Then I'll tag them with question. Just include "[Question]" or a question mark in the title, or nothing at all.

**Pull request merged**
