### PR TITLE
Add --no-color option to `crystal spec` subcommand

### PR DESCRIPTION
**Pull request by rhysd**
I added `--no-color` option to `spec` subcommand.  This is already discussed at #1587.

### CODE REVIEW

**Comment by rhysd** [comment]
Now `spec` subcommand ignores options which starts with `--`.  This implementation is OK?

**Comment by jhass** [comment]
+1 for `use_colors`

**Comment by rhysd** [comment]
@luislavena @kirbyfan64 @jhass 

I renamed `color` to `use_colors`.

**Comment by jhass** [comment]
Looks good, could you squash your commits together?

```sh
git remote add upstream https://github.com/manastech/crystal.git
git fetch upstream
git checkout spec-no-color
git rebase -i upstream/master
# Leave the first commit at pick, choose squash or fix for the others.
# If there are any conflicts git will inform you about that, resolve them for
# example with git mergetool or manually and with git add, then run
# git rebase --continue, again  watch the output since that might happen for
# each commit.
git log # Look at the updated commit history
git status # should report you're back on your branch
# We need to force push since a rebase edits the commits, effectively
# creating new ones. This is okay to do in a feature branch, the pull
# request will update.
git push -f origin spec-no-color # Assuming you cloned from your fork
```

Hint: You can also edit your last commit with `git commit --amend`, since that also effectively creates a new commit, you to need to force push afterwards and again you should only do it in feature branches.

**Comment by rhysd** [comment]
@jhass 

Squashed!

**Comment by jhass** [comment]
Thanks!

**Pull request merged**
