### PR TITLE
Added specs for SimpleHash

### PR DESCRIPTION
**Pull request by Exilor**

### CODE REVIEW

**Comment by Exilor** [comment]
Fails because #471 hasn't been merged yet.

**Comment by asterite** [comment]
Thanks!! In #471 I was talking about specs for `to_s`, but you added so much more. Awesome!

By the way, did you know you can write:

```crystal
require "simple_hash"

hash = SimpleHash { "foo": 1, "bar": 2 }
puts hash
```

You can create custom Hash-like objects with this syntax, as long as the object has the `[]=` method. The same applies for Array-like objects, as long as they have a `<<` method:

```crystal
Set { 1, 2, 3 }
```

**Comment by Exilor** [comment]
Oops I thought you meant specs for the whole thing...
I knew that you could do things like ```Set {1, 2, 3}``` but I didn't know that it could be done with hash-like objects. It looks much better that what I wrote in the specs. Should I I change it?

**Comment by asterite** [comment]
Not "Oops", it's great if we have more specs! :-)

If you want to change it, go ahead, but it's not super necessary.

**Pull request merged**
