### PR TITLE
Handle web socket close packet + add send method to web socket sessio…

### PR DESCRIPTION
**Pull request by bebac**
…n class

A couple of improvement to the web socket handler.

* Adds an on close event handler to web socket session
* Add a send method to the web socket session

Example
```
HTTP::WebSocketHandler.new do |session|
  session.on_message do |msg|
    if msg =~ /^ping/
      session.send("pong")
    end
  end

  session.on_close do |reason|
    STDOUT.puts "channel closed"
  end
end
```

### CODE REVIEW

**Comment by jhass** [comment]
Mmh, how about renaming these to `on_message` / `on_close` btw?

**Comment by bebac** [comment]
It's fine by me, but it will break it for those already using onmessage

**Comment by jhass** [comment]
That's what the pre 1.0 phase is for.

**Comment by bebac** [comment]
Ok, I will rename onmessage and onclose

**Comment by jhass** [comment]
Well, it's just my opinion, maybe wait a bit to see what others think

**Comment by bebac** [comment]
I like it better too. It's more consistent with the general naming convention, as far as I can tell.

**Pull request merged**
