### PR TITLE
Add other combinations methods

### PR DESCRIPTION
**Pull request by kostya**

### CODE REVIEW

**Comment by asterite** [comment]
You are A-W-E-S-O-M-E !!! Thank you so much!

I'll just change those `[x] * n` to `Array.new(n, x)`. I don't think it will affect the overall performance, but the less we allocate, the better.

**Comment by kostya** [comment]
main slowness is a `pool[0, size]` which is in custom case is `pool.dup`. and seems topaz can remove it, when it know that pool not stored to anywhere and just used only in block. if crystal can be so smart...

**Comment by asterite** [comment]
@kostya You mean arrays are shared and only copied on modification?

**Comment by kostya** [comment]
not only modification, store to some place make copy too.
` x = [] of Array(Int32); [1,2,3].each_combination { |pool| x << pool }; x`

**Pull request merged**
