### PR TITLE
Add a new compiler option `--path PATH`

### PR DESCRIPTION
**Pull request by MakeNowJust**
The option `--path PATH` is to add path to find required files. This PR is connected to #1949. What I really need is the system to inject the path externally.

### CODE REVIEW

**Comment by asterite** [comment]
Why do you need this? Dependencies can go into the `lib` directory.

**Comment by MakeNowJust** [comment]
@asterite I explained in #1949. For example, when I am at src directory in the crystal project, I often want to run script using project's dependency. In such a case, I think this option works well.

**Comment by asterite** [comment]
Why not run crystal from the root directory?

**Comment by MakeNowJust** [comment]
Why not not run crystal from the root directory? We can't have the liberty to run crystal from any directory?

For example, when in development, I often dive under `src/` directory, then write code and run it to check (Why? Main reason is to reduce the count of types in the terminal). This is not kind of problem to resolve `libs/` directory implicitly, but no method to resolve is nonsense. So I want the compier to provide `--path` option.

**Pull request closed without merging**
