### PR TITLE
Implement Enumerable#none? without block

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
```
Returns `true` if all of the elements of the collection is `false` or `nil`.
```

I think you mean ``are `false` ``?

**Comment by yui-knk** [comment]
Do you mean 
> Returns `true` if all of the elements of the collection are `false` or `nil`.

?

**Comment by kirbyfan64** [comment]
@yui-knk Yes.

**Comment by yui-knk** [comment]
thx!

**Comment by asterite** [comment]
Thanks!

**Pull request merged**
