### PR TITLE
Add `class_name` macro method

### PR DESCRIPTION
**Pull request by yui-knk**
In crystal some Literal objects have few macro method, and others
have many macro method.
For example BoolLiteral has few macro method
(`id`, `stringify`), NumberLiteral has many macro method (`>`, `+` etc).

So I think `class_name` macro method which returns the name of Literal
is usefull and implement it.

### CODE REVIEW

**Comment by yui-knk** [comment]
But

```
assert_macro "", "{{:foo.class_name}}", [] of ASTNode, "\"SymbolLiteral\""
```

and

```
assert_macro "x", "{{x.class_name}}", [SymbolLiteral.new("hello")] of ASTNode, "\"SymbolLiteral\""
```

tests are failed.
Both of theme return `":StringLiteral"`, I feel it may be bug related to `class_desc`.
Can someone help me?

**Comment by asterite** [comment]
I think this might be a useful methods in macros. But you can also use `is_a?`. Why do you need the class name of nodes?

**Comment by yui-knk** [comment]
I think this method is the method to debug macro.
For example, in these macro

```
macro define_method(name, content)
  def {{name}}
    {{content}}
  end
end
```

`name` and `content` are not normal class (maybe HogeLiteral). This causes panic who is not familiar with Crystal lang.

In these case, users can inspect the class by using `class_name`.

**Comment by yui-knk** [comment]
@asterite I fixed some bugs. Can you merge this? :)

**Comment by asterite** [comment]
Thanks. This is probably useful to quickly know the name of a node so you can later use it with `is_a?`. Otherwise you'd have to dig in the compiler's source code to find this out (or the missing grammar).

**Comment by yui-knk** [comment]
> or the missing grammar

Yes, yes!
Thanks for merging :)

**Pull request merged**
