### PR TITLE
Fix #1509 String escapes don't work with symbols

### LINKED ISSUE #1509: String escapes don't work with symbols
http://carc.in/#/r/frm:

```crystal
puts :"1" # Ok
puts :"\"1" # Error
```

Even if this isn't intended behavior, could the error message be a bit better?

### PR DESCRIPTION
**Pull request by wolflee**

### CODE REVIEW

**Comment by jhass** [comment]
Awesome! Do you think you could add a spec?

**Comment by wolflee** [comment]
Totally n00b on compiler things, I'll give it a try this weekend. Any advice is welcomed.

**Comment by jhass** [comment]
I think adding an example or two [here](https://github.com/manastech/crystal/blob/master/spec/compiler/parser/parser_spec.cr#L170-L179) should be good enough.

**Comment by wolflee** [comment]
Thanks for the tips~ specs added.

**Comment by jhass** [comment]
Looks great! Any chance you could squash the commits together?

```sh
git remote add upstream https://github.com/manastech/crystal.git
git fetch upstream
git checkout fix_string_escapes_in_symbols
git rebase -i upstream/master
# Leave the first commit at pick, choose squash or fix for the others
# If there are any conflicts git will inform you about that, resolve them for
# example with git mergetool or manually and with git add, then run
# git rebase --continue, again  watch the output since that might happen for
# each commit.
git log # Look at the updated commit history
git status # should report you're back on your branch
# We need to force push since a rebase edits the commits, effectively
# creating new ones. This is okay to do in a feature branch, the pull
# request will update
git push -f origin fix_string_escapes_in_symbols # Assuming you cloned from your fork
```

Hint: You can also edit your last commit with `git commit --amend`, since that also effectively creates a new commit, you to need to force push afterwards and again you should only do it in feature branches.

**Comment by kumpelblase2** [comment]
@jhass given that squashing PRs into one commit comes more and more present, it would probably make sense to just add it to the `Contributing` guide.

**Comment by jhass** [comment]
It's something I prefer, I don't think I entirely convinced @asterite and @waj about it yet ;P

**Comment by asterite** [comment]
We can add it to the `Contributing` guide so the commit history is cleaner, yes :-)

**Comment by wolflee** [comment]
Also preferred cleaner commit logs, will do the squash when got home.

发自我的 iPhone

**Comment by wolflee** [comment]
Done.

**Comment by jhass** [comment]
Thank you!

**Pull request merged**
