### PR TITLE
Add support for  stderr access to Process.run and refactor it

### PR DESCRIPTION
**Pull request by jhass**
This also allows redirecting the childs stderr to it it's stdout and vice versa.

### CODE REVIEW

**Comment by jhass** [comment]
If it would just work on OS X,  that would be too easy, eh?

**Comment by r20** [comment]
@jhass sounds like you should buy a mac, just for Crystal dev :-P

**Comment by asterite** [comment]
@jhass that's an llvm error on travis, it seems it's a bug in Crystal, not in your code

**Comment by jhass** [comment]
Yeah, but still... it's just running perfectly on my box :(

**Comment by jhass** [comment]
Oh, notice it's happening on the first commit already, might make it easier to debug :)

**Comment by asterite** [comment]
https://github.com/manastech/crystal/commit/bbf2036d49a7b7d245852330c3697d73ff6fc2d9

**Pull request closed without merging**
