### PR TITLE
spawn: print exception class and backtrace to stderr

### PR DESCRIPTION
**Pull request by jhass**

### CODE REVIEW

**Comment by jhass** [comment]
I'd even ponder to `exit!` in that case, what do you think?

**Comment by technorama** [comment]
Should error/exit functionality be standardized?  Maybe a method or 2 on Exception like fatal_exit() or pretty_print(io = STDERR) followed by exit!

**Comment by jhass** [comment]
Updated to use the new method from #1300

**Comment by asterite** [comment]
@jhass :+1:

**Pull request merged**
