### PR TITLE
Implement Enumerable#sort

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by PragTob** [comment]
Looks good :+1:

**Comment by asterite** [comment]
Thanks!

But... do we really want to copy these methods from Ruby? An Enumerable can't define `sort` efficiently without turning the elements into an array first. I think having to explicitly do `enumerable.to_a.sort!` (or something similar) isn't bad, because it shows that there's an intermediary array creation. This might suggest that maybe you should be using another data structure for the problem. Plus, it's really not that long to type `to_a.sort`.

But that's just my opinion. What do others think?

**Comment by yui-knk** [comment]
I think Enumerable has `sort` method is reasonable. In other method, an intermediary data structure change is happen (ex: `each_slice` or `each_cons` ).

**Comment by juanedi** [comment]
I'm with @asterite on this one. Having an intermediate data structure for implementation purposes is fine, as long as the method itself makes sense for Enumerable.

To me the great difference between an Enumerable and a finite collection is precisely that: you can't expect the numerable to always be convertible to an array. I'd rather not have this handy method but mantain an API that is semantically sound.

**Comment by PragTob** [comment]
I like what @asterite is saying - and I use it as an example when talking to other people about differences between ruby/crystal. I think it's reasonable to do `to_a.sort` to show the creation of the intermediary array :)

**Comment by asterite** [comment]
I'll close this. Invoking that intermediate `to_a` isn't a big deal, and it's better not to have too many "just forwards" methods.

**Pull request closed without merging**
