### PR TITLE
WIP: Matrix

### PR DESCRIPTION
**Pull request by Exilor**
This is an ongoing, liberal adaptation of Ruby's Matrix class. Some of the most "mathy" methods haven't been implemented yet. Your feedback would be appreciated :)

### CODE REVIEW

**Comment by asterite** [comment]
Looks really nice! :-)

Two comments:
1. Instead of `io << e.inspect` you can do `e.inspect(io)`. In that way you don't create a temporary string.
2. I tried doing `Matrix[[1, 2], [3, 4, 10]]` and it didn't raise a runtime error (in Ruby it does).

I also used the Matrix in the [conway sample](https://github.com/manastech/crystal/blob/master/samples/conway.cr) and it worked flawlessly. It also made the program (just a bit) faster.

So this is really good. Please continue it! :star2:

**Comment by Exilor** [comment]
1 & 2: Done
I'm still unsure of what to do with ```#to_s```. In the Ruby version it's the same as #inspect but I think it would be nice if it provided a way to visualize the matrix as a matrix instead of an array of arrays like #inspect does. Although as it is now it only looks good when its elements have a string length of 1. What do you think, like Ruby or shall I look for a cleverer way to make it look good?

BTW it looks like I had a brainfart and a commit for another thing (056603e) has been lumped here. Is there a way I could remove it?

**Comment by jhass** [comment]
Yeah, you should create topic branches.

```bash
# Some base setup
git remote add upsteam git://github.com/manastech/crystal.git
git fetch upstream

# Interactive rebasing towards a clean history,
git checkout topic_branch # In this case you committed to master, so choose that
git rebase -i upstream/master # The target of your pull request
# You can just remove lines here to drop commits you can also reorder them, but
# that quickly causes conflicts, so be careful
# squash and fix allow you to combine multiple commits into one,
# you can combine this with reordering
# edit pauses the rebase at that point, you can edit the commit with
# git commit --amend and continue the rebase with git rebase --continue
# After the rebase you actually have a set of completely new commits, so you need to
# force push:
git push -f origin topic_branch # Where origin is your fork, in the topic_branch again master in this case

# Partial committing
git add -p # Select individual diff hunks into the staging area
git commit -p # Select individual diff hunks and commit them (+ everything in the staging area)
git checkout -p # Select individual hunks to discard

# After this PR, get to a clean state for the future
git fetch upstream
git branch -D master
git checkout -b master upstream/master

# Create a topic branch for future PRs
git fetch upstream
git checkout -b my_feature upstream/master

**Comment by Exilor** [comment]
Thanks @jhass, I'll try that in my next pull request :) luckly that particular commit was harmless.

**Comment by jhass** [comment]
Doesn't mean there's no opportunity to clean up the history here... ;)

**Comment by Exilor** [comment]
You see, I'm a bit afraid of messing something up.
Following your instructions:

git remote add upsteam git://github.com/manastech/crystal.git
git fetch upstream
git checkout master
```
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
	.travis.yml

```
And I kinda got stuck here.
I really don't want to be a bother with my git newbieness. That's why I usually do things via github instead of the command line.

**Comment by jhass** [comment]
Nah, helping git newbies is fun ;)

What's your `git status` and `git diff` outputs?

**Comment by Exilor** [comment]
I got past that error. However, ```git rebase -i upstream/master``` appears empty (noop at the top).
What I did with the initial pull request was this:
  -I forked the repo clicking "fork" at ```https://github.com/manastech/crystal```
  -I manually created ```matrix.cr``` at ```/src and matrix_spec.cr``` at ```/specs/std``` in my fork and pasted their respective contents from my local files.
I'm guessing that's why the rebase is empty :/

**Comment by jhass** [comment]
yes, you probably never pulled your changes locally. Let's fix that and ensure your local clone's origin remote is your fork, then pull the changes:
```
git remote set-url origin git@github.com:Exilor/crystal.git
git fetch origin
git checkout master
git pull origin master
```

**Comment by Exilor** [comment]
Looks like it worked.

**Comment by jhass** [comment]
Yup it was rebased. Now personally I would use the interactive rebase to combine the commits into one ;)

**Comment by Exilor** [comment]
Done. But what does that accomplish? A cleaner commit?

**Comment by jhass** [comment]
Yes, a cleaner git history. That's particularly useful for easier reverting in case that new functionality causes troubles, `git blame` to get the whole changeset in that a line was introduced and `git bisect` in order to find the commit/functionality that introduced a problem.

**Comment by Exilor** [comment]
The class is already functional. More niche things like eigensystem, lup_decomposition etc. can be added later once I figure how they work in Ruby and how to replicate them here, or if some brave soul wants to contribute that'd be cool too.
I think it's ready to be merged.

**Comment by jhass** [comment]
Here's another tip: You can edit issue/pull request titles, for example to remove a "WIP" flag ;)

**Comment by Exilor** [comment]
Yeah I know :)

**Comment by asterite** [comment]
I have a few changes in mind. Could you make them please? After these changes I'll finally merge it :-)

* We changed `Range(B, E)` to `Range(T)`, and there are a couple of methods that check against `Range(Int, Int)`. They should check against `Range(Int)`.
* `def_hash` is not quite right, because it bases its value on the pointer's hash. But a pointer doesn't know its length, so a pointer's hash is just its address. To do the hash correctly you'd have to compute a hash based on the matrix's value. See how [Array](https://github.com/manastech/crystal/blob/master/src/array.cr#L355) does it.
* The check for index out of bounds raises if `index >= size`. But what happens if index is negative? That check is missing in a lot of places. For example this segfaults: `puts Matrix[[1]][-10000000, -10000000]`. The problem is that you do `index += size if index < 0`, but that can still lead to a negative value if index is a very large negative number. See how [Array](https://github.com/manastech/crystal/blob/master/src/array.cr#L368) does it.
* Maybe `map`, `map!`

**Comment by Exilor** [comment]
- Done
- Done
- Done
- ```#map``` & ```#map!``` done. I didn't do it that way because Array doesn't yield the index with ```#map``` either, just the elements. ```#index``` though... what would you use the indices for? If you want the element at a certain index you can use ```#at``` or ```#[]```.

**Comment by Exilor** [comment]
Committed.

**Pull request merged**
