### PR TITLE
Enumerable.min & max accept a default value.

### PR DESCRIPTION
**Pull request by technorama**

### CODE REVIEW

**Comment by asterite** [comment]
:+1:

**Comment by jhass** [comment]
One issue I see is that this doesn't allow to use `nil` nor `false` as the default and that they behave differently (raising or not) depending on passing (a truthy) value or not. I still have to think more about this, but perhaps do overloads?

**Comment by asterite** [comment]
@jhass I thought about that too. However, `Nil` and `Bool` usually don't participate in ordered stuff, unlike integers, strings, and other types. Normally you'd want the `default` to be of the same type as the elements in the collection, and you usually don't get the max of something with `Nil` or `Bool` inside it.

**Comment by bcardiff** [comment]
What about adding Enumerable#append that will just yield one last value that can be used as a default for it.append(42).min ?









—

**Comment by jhass** [comment]
Well, given they raise, `possibly_emtpy.min(nil) || compute_expensive_default` is actually a valid usecase IMO:

**Comment by technorama** [comment]
Should min & max return nil on empty and the default option be removed?  Or new methods added?

[].max? || 0
[].max || 0

**Comment by bcardiff** [comment]
+1. I like better the #max? Alternative than the default argument. Leaving #max raising if empty



—

**Comment by asterite** [comment]
I like the `max?`, `min?`, etc. variants and doing `[].max? || 0`, as @technorama suggested. I was going to suggest that myself too :-) It is consistent with the rest of the language and pretty easy to use. And `max` can be easily implemented on top of `max?`.

If we decide to do that, we might want to change `Enumerable#index` to raise and add `index?`, and the same goes for `find`.

**Comment by technorama** [comment]
@asterite: Done.  

I'm not changing index.  Almost all uses of index use `if index; a; else b` where `else` does something other than raise an exception or ignore it.  Perhaps the normal usage of index is maybe(nil) type logic?

Also it was way more work than expected.

**Comment by jhass** [comment]
I think this is good enough for now, we can handle `index` later, worst case we replace all existing `index` usages with `index?`

**Comment by asterite** [comment]
Yes, we can probably leave `index` like that.

**Pull request merged**
