### PR TITLE
Added Number::[]

### PR DESCRIPTION
**Pull request by Exilor**
As requested.

### CODE REVIEW

**Comment by jhass** [comment]
What's wrong with my oneliner? It even handles the overload case.

**Comment by asterite** [comment]
I was actually thinking of accepting the pull request and changing the implementation to this:

```crysal
struct Number
  def self.[](*nums)
    ary = Array(self).new(nums.length)
    ary.length = nums.length
    nums.each_with_index do |num, i|
      ary.buffer[i] = cast(num)
    end
    ary
  end
end
```

That's a bit unsafe, because it accesses the Array's internal buffer, but in that way you avoid the bound checks. But it's actually safe because the methods knows the length, so...

The one-liner accesses the tuple by an index unknown at compile-time, so a runtime check will be left there.

**Comment by Exilor** [comment]
I tried it before and look:
```ruby
struct Number
  def self.[](*nums)
    Array(self).new(nums.size) {|i| cast(nums[i]) }
  end
end

UInt16[] # => expected block to return T, not NoReturn
```

**Comment by jhass** [comment]
Interesting, `Array(Int64).new(0) {|i| Int64.cast(i) }` works, it breaks with passing `size` of an empty tuple.

**Comment by asterite** [comment]
I'll check that later, I think the compiler can't figure out what's the type of `cast(nums[i])` because that line will never be reached for an empty tuple. In any case, it's a bug of some sort.

**Comment by asterite** [comment]
Anyway, I'll accept it, change it to the faster version and add some specs :-)

Thanks!

**Pull request merged**
