### PR TITLE
Add note to option_parser

### PR DESCRIPTION
**Pull request by adlerhsieh**
Add note: options setup through option_parser work only after build.

### CODE REVIEW

**Comment by jhass** [comment]
I'm not sure this is the right place to document this. For example `crystal run --help` says:
```
Usage: crystal run [options] [programfile] [--] [arguments]
```

Maybe people get tripped up by the `[options]` there? Should we call it `[compiler options]`?

**Comment by adlerhsieh** [comment]
I think `options` is ok in `crystal run --help`. I document this because I only realise this after several tries, but I see your point that this might be a minor piece of knowledge here.

**Comment by adlerhsieh** [comment]
I will reopen it if I find a need or a right place to document this idea.

**Comment by jhass** [comment]
I really have no objections in explaining that behaviour  somewhere, even though it's common for tools that parse & run a program (ruby has essentially the same behaviour). I just don't  think this is the right place, though I'm not sure what it is :)

Maybe here already? http://crystal-lang.org/docs/using_the_compiler/index.html

**Comment by vyp** [comment]
Yep this is a pretty common scenario, to use `--` to specify arguments to the underlying program. Nevertheless, it's probably still useful to clarify this behaviour, but probably in the docs where @jhass suggests, rather than in the source code here.

**Pull request closed without merging**
