### PR TITLE
Add in_groups_of for enumerable

### PR DESCRIPTION
**Pull request by jalyna**
Taken over from http://guides.rubyonrails.org/active_support_core_extensions.html#grouping

### CODE REVIEW

**Comment by asterite** [comment]
Thanks! I always wondered why this pretty useful method was never backported to Ruby's standard library.

If you don't mind, I'll merge this and make a few changes:

1. Check that `size > 0`, otherwise raise `ArgumentError` saying `size must positive` or something like that. 
1. Define a single method with a default argument `def in_groups_of(size : Int, filled_up_with = nil : U)`. But... it seems that doesn't work, I get an `undefined constant U` error, maybe you tried to do the same and got the same error so decided to do two overloads. I just created a [bug report](https://github.com/manastech/crystal/issues/1101) for this. Still, we can solve this with a single overload using `typeof(filled_up_with)`, as a workaround until we solve that bug.
2. Use `Int` instead of `Int32` as a type restriction, so it doesn't matter if it's Int32, Int64, Int8, etc.
3. Add an overload that accepts a block, the method would yield the groups to the block. Using this you can also implement the non-block version.

That is, unless you want to do those changes :-)

**Comment by jalyna** [comment]
@asterite Thank you so much for your feedback. I would like to try to implement those changes :smiley:

**Comment by jalyna** [comment]
@asterite I updated my pull request.

**Comment by asterite** [comment]
Thanks again!!

**Comment by kostya** [comment]
each_cons seems doing the same?

**Comment by asterite** [comment]
@kostya Yes, except `in_groups_of` allows you to specify a filler. I also noticed this duplication. In ActiveSupport you can pase `false` for the filler which means "don't use a filler" (thus being the same as `each_slice`, I think), which I don't think it's nice (it's a variant of the [semipredicate problem](https://en.wikipedia.org/wiki/Semipredicate_problem)), because what if you want to fill with `false`? So I think having two methods is better.

But, we can always discuss alternatives so we don't have with too many similar methods.

**Pull request merged**
