### PR TITLE
Adds a bunch of documentation to array

### PR DESCRIPTION
**Pull request by zamith**
This is a WIP, but wanted to get some feedback on both the docs and on why array was not on them. Is there any particular reason, or is it just that no one had gotten to them yet?

### CODE REVIEW

**Comment by asterite** [comment]
Thank you!

It looks good. I'm not sure about "given that the type of the value belongs to the union type of the array", I think that's clear because of the `T` restriction, but if you want to leave it that's ok (but `T` might not be a union).

Most classes are not documented because of lack of time. I think documentation is paramount, specially because of the differences from Ruby, so any pull request containing docs is more than welcome!

**Comment by zamith** [comment]
You mean that T might be a plain type or a union type? I guess it could be explained more clearly, sure. I'll give it a go.

Yes, I think it is very important to attract new people to contribute to the language. I was trying to follow Rails' philosophy, that all methods are documented except for private ones that are tagged with `:nodoc:`. What do you think?

**Comment by asterite** [comment]
@zamith That's fine. Right now private methods aren't documented, so there's no need to use `:nodoc:` for them. We do have to use `:nodoc:` because there's no concept of a private type.

**Comment by zamith** [comment]
Ok. I'll keep documenting away then.

**Comment by asterite** [comment]
@zamith I decided to merge this so we don't have many open pull requests. More docs for Array are always welcome. Thanks! :-)

**Pull request merged**
