### PR TITLE
Change waitpid handler to use a future.

### PR DESCRIPTION
**Pull request by technorama**
Remove Process::WaitpidFuture.

### CODE REVIEW

**Comment by jhass** [comment]
For some reason this balloons memory allocation while compiling all_spec. While master stays constant at about 2.1G RES and a bit more VIRT than that, this branch for me locally too exhausts address space, showing similar usage in RES but ballooning VIRT until it fails.

**Comment by jhass** [comment]
So changing to `lazy` instead of `future` solves the memory issue. Do you have investigating why it happens with `future` on your todo list?

**Comment by technorama** [comment]
@jhass I would consider memory ballooning a compiler/runtime problem and not a problem in this PR.  I have no plans to investigate before 30 or so other projects are completed.

**Comment by jhass** [comment]
Well, I think it's a 50% chance it's caused by code you contributed I'd say.

**Comment by technorama** [comment]
Triggered by does not mean the root cause is my code.  `future {}` is nothing more than a class, spawn and channel combined.  2/3 of that is already in the existing waitpid handler.  The new thing is spawn or the particular order of operations.  

I don't see a reasonable cause for memory ballooning.    There are no loops or big allocations.

**Comment by waterlink** [comment]
Maybe something that LLVM was able to optimize before, now it can't? Might be worth looking at LLVM IR, that both versions would generate.

**Pull request merged**
