### PR TITLE
fix bug IO.copy returning wrong count if dst didn't write everything

### PR DESCRIPTION
**Pull request by jreinert**

### CODE REVIEW

**Comment by asterite** [comment]
I'd break if `write_len` is zero, not if it's different than what you read.

**Comment by jreinert** [comment]
why? how should i continue if it's less than read size? try again? just ignore and continue from where i left off?

**Comment by asterite** [comment]
Maybe you couldn't write it in that call but you'll be able to do it in the next one?

Also, what happens with the bytes that you read but didn't write? They are lost.

**Comment by jreinert** [comment]
hmmm... I don't know about that. It will be easier for the dev using the function to react accordingly if he or she get's back an unexpected size: seek the input io to the correct position and try again or raise or what ever. If it continues to write to the output and as you said, bytes being lost, the dev will have no way of knowing which part failed to copy.

**Comment by bcardiff** [comment]
I think it depends on the contract of `IO#write`. `IO#read` is not guaranteed to fill all the slice but reading nothing means EOF. 

So `IO#write` should not guaranteed to consume the whole slice. But consuming nothing should mean unable to write now or ever.

Considering this, the copy should keep trying to write all the read slice until no data is written.

**Comment by asterite** [comment]
I agree with @bcardiff . Writing less than what you requested is not an error, just temporary inability to write everything.

**Comment by technorama** [comment]
@asterite Where is it possible to write less than you requested without a closed IO?  

`FileDescriptorIO#unbuffered_write` uses `wait_writable` to retry internally.  It either writes what was requested or raises.

`BufferedIO#write` can't handle partial writes and retries.  If flush fails mid write data will be lost.  This isn't an issue with `FileDescriptorIO` since it retries internally or raises.

Are there other IO's that can fail temporarily without using wait_writable?

**Comment by jreinert** [comment]
@asterite alright, I bend to your and @bcardiff's will :smile_cat: I updated the method and merged master for the fix to #1642

**Comment by waj** [comment]
As explained in #1652 and also in agreement with what @technorama said here, we need to make sure that for all `IO` implementations, `write` will either write all the contents or raise. I'd event change `IO#write` so it doesn't return the bytes written (always the size of the slice).

**Comment by jreinert** [comment]
ok so `IO#write` should have no specific return value but raise an error as soon as not everything was written? what about signals? if a write is interrupted by one as @waj explained in #1652?

**Comment by asterite** [comment]
@jreinert No progress on this yet, we need to review `IO#write` with @waj and we'll get back to you

**Comment by waj** [comment]
Not applicable anymore after 0ece5cbb15a6005b355d932ba3d737beb84ceffc

**Pull request closed without merging**
