### PR TITLE
Add `Array#slice` and `Arrat#slice!`

### PR DESCRIPTION
**Pull request by tebakane**
I added slice and slice! methods in Array class.

```ruby
a = [1,2,3]
a.slice!(1)  #=> 2
a                #=> [1,3]
```

### CODE REVIEW

**Comment by jhass** [comment]
Mmmh, `slice` seems redundant to `[]`, no? And `slice!` at least partially to `delete_at`

**Comment by tebakane** [comment]
Actually Yes. `slice` is useless. It originate from Ruby's slice method.
Just I like to add `slice!(index, count)` and `slice!(range)` method.
Do you think it is better to expand `delete_at` method?

**Comment by jhass** [comment]
I think so, yes. Having `slice` is redundant to `[]`, but having `slice!` without `slice` is confusing to the Rubyist.

**Comment by tebakane** [comment]
I see. Instead of  `slice!`, I will expand `delete_at` like `delete_at(index, count)` and `delete_at(range)`.

**Comment by jhass** [comment]
Great!

**Comment by tebakane** [comment]
Please close it. Thanks.

**Pull request closed without merging**
