### PR TITLE
Adds the bit reference method to Ints

### PR DESCRIPTION
**Pull request by zamith**
This is a little convenience method, especially for those working actively with binary numbers. I've written it in a very quick and dirty way. I'd love feedback on better ways of doing it.

### CODE REVIEW

**Comment by BlaXpirit** [comment]
In my opinion, this addition is unnecessary and counterintuivive.

"n-th item of an integer" is nonsense.
Why is base-2 so special?

And the implementation is sloppy and buggy (negative numbers?).

---

Disclaimer: I'm not an active contributor, so feel free to disregard.

**Comment by kirbyfan64** [comment]
This was explicitly labeled as "not wanted" because of the potential for bugs, though now I can't find the exact issue number.

**Comment by kirbyfan64** [comment]
(However, a method to do this *would* be nice...)

**Comment by kirbyfan64** [comment]
I think it could be something like:

```crystal
def bit(n : Int)
    (self >> n) & 1
end
```

**Comment by zamith** [comment]
@kirbyfan64 That's so much nicer. Thanks. :)

I had no idea this had been previously discussed, but would like to know the reasoning to it being marked as not wanted. Also call @chastell to the conversation, as one of the few people I've seen using this method in actual code.

**Comment by asterite** [comment]
It was discusses in #981. And there's [Int#bit](https://github.com/manastech/crystal/blob/master/src/int.cr#L171-L173).

**Comment by zamith** [comment]
That's fine then. Feel free to close the pr. ;)

**Comment by chastell** [comment]
Oh, and here I was yesterday evening fighting with the right way to put the proper libpcl version into `LIBRARY_PATH` to get `make spec` pass on Ubuntu 14.04 – to propose `Int#[]`. :)

I agree with `Int#bit` being a better name; the `[5, 4, 3][2][1][0]` example is quite convincing.

I have zero LLVM experience – is `self & (1 << bit) == 0 ? 0 : 1` better/safer than `(self >> n) & 1` or are they equivalent? Do they compile to the same LLVM instructions?

**Pull request closed without merging**
