### PR TITLE
Logger: Flush log messages.

### PR DESCRIPTION
**Pull request by technorama**

### CODE REVIEW

**Comment by Nakilon** [comment]
Maybe I don't know something about Logger practices, but in Ruby I would leave changing buffer size to `io_object.sync = true` if needed.

**Comment by ysbaddaden** [comment]
I have to test it first. I know that forcing file.sync = true fixes the issue. I suppose flush would achieve the same, and avoid writing twice (first the message then the linefeed).

I'm just wondering about parallelism: would both (message + linefeed) always happen atomically, or should the formatter inject the linefeed itself, so we're sure there is just a single write, and 2 messages won't be collapsed on a single line?

**Comment by technorama** [comment]
With multithreaded concurrency there is a problem.  With fibers probably not unless you write to something that can block (pipe/socket).

```
io << "foo" << "bar" # all separate writes.  
puts ""
```

With fibers (single thread):
  Any of the individual writes can switch to another fiber but only if it's to a socket, tty, or pipe.   Files are safe as they never return EWOULDBLOCK.

With threads:
*  Your log messages will get corrupted.
*  The only ways to handle this are either A) a mutex or B) Putting the message in a single buffer (StringBuilder?) and using write && reworking the internals of unbuffered_write to always resume a fiber with a partial write before switching to others && making BufferedIO thread safe.  Note: currently multiple readers/writers are not thread safe on an individual IO.  Fibers can get lost and the program will deadlock.

The only way to handle this correctly in all situations is with a mutex or complex atomic ops in multiple methods.

I would suggest making IO only single fiber safe and using a thread safe mutex backed wrapper for the rare occasion (like logging) where multiple Fibers/Threads write to the same IO.  Otherwise the same problem will happen in many libraries by assuming IO is thread/fiber safe.

**Comment by technorama** [comment]
Consider this PR good enough until multiple threads are possible in crystal.

**Comment by Nakilon** [comment]
I thought the thread unsafety when logging is common for any language and setting buffer size to zero explicitly is ok.

**Comment by technorama** [comment]
@nakilon Concurrency safe logging is often application specific.  Consider an application that wants multiple log lines grouped together but the logger api only allows a single line at a time.

```
mutex.synchronize { logger.info; logger.info; ... }
```

is one possible solution but you will need a completely different one if the application forks.

In the short term flushing is probably good enough.  Using mutexes can cause deadlocks without threads.  This and many other classes will need changes when threads are available.

**Comment by ysbaddaden** [comment]
Thanks for the detailed explanations. Flushing looks enough for now, since we're logging to files.

Later we could wrap Formatter inside a String.build to have a single write (depending on low level C function atomicity).

**Pull request merged**
