### PR TITLE
Cleanup gh-pages setup

### PR DESCRIPTION
**Pull request by jhass**
* Use the github-pages gem
* Update config to updated versions
* Correctly choose no layout for feed.xml

Not sure if that breaks any of your local setups, for me it fixes it (`bundle exec jekyll serve` works now), thus pull request ;)

### CODE REVIEW

**Comment by 5t111111** [comment]
:+1: for this.
I'm working on the japanese translation, but I had to manually modify Gemfile to update the gems to the latest ones, otherwise jekyll always failed to build static pages (there were a lot of errors in safe_yaml).
I'm not sure if adding github-pages gem is the best way to solve the problem either.

**Comment by jhass** [comment]
It's recommended by Github.

**Comment by bcardiff** [comment]
On a related note, @jhass you in the past you [changed the .ruby-version](https://github.com/manastech/crystal/commit/2dbe7275d76e40074578d469d140248f9bd42438#diff-0d75b3c58057105d6c02c1fd3827050d) to `2.2`. Are you using rbenv-aliases or similar, right? Any reason to not point to `2.2.2`?

**Comment by jhass** [comment]
The reason is I'm not using rbenv at all, both chruby and RVM are just fine with picking up the latest available release of a series with that specification. Only rbenv falls out of the line here and that by design, it's in fact the most significant reason I recommend chruby or RVM over rbenv.

**Comment by 5t111111** [comment]
Since all of I and others who are working on the japanese translation are using rbenv for the moment,  we are very grateful if you could revert the changes to make `.ruby-version` work out of the box. In addition, I think specifying a teeny version is better than the implicit latest version In many cases.

**Comment by jhass** [comment]
It was better during the 1.9 and 2.0 days, but these days, excuse my harsh words, it's just annoying. The teeny versions are really compatible between each other and I don't want to have all of them installed, it's just wasting resources. Especially for a project like this which would actually be fine without any `.ruby-version` file at all.

I'd recommend you to create an alias named `2.2` pointing to the latest version, see https://github.com/tpope/rbenv-aliases

**Comment by 5t111111** [comment]
Thank you for your response. I see. I'm going to try rbenv-aliases.

**Comment by vyp** [comment]
I hate to be interrupting with off-topic comments, but it looks like you guys are having some ruby versioning problems (I'm not terribly familiar with the ruby ecosystem), but I came across this article recently and I'll leave a link here in case it helps you guys: http://dthompson.us/ruby-on-guix.html (Heads up, before you decide to read it, afaik Guix only works in GNU Linux.)

**Comment by waterlink** [comment]
@vyp ruby-on-guix is interesting, but it is not a standard way to manage ruby versions.

I would agree with @jhass and recommend RVM or chruby.

What about removing `.ruby-version` at all? I think gh-pages project does not need it to be restricted? Or am I wrong?

**Comment by bcardiff** [comment]
I'm fine adding an alias to 2.2, I just wanted to be sure why was the change. 
In other than static page projects I wouldn't thou, if each dev box have their own version alias it defeats the purpose of the .ruby-version (maybe only if you use rbenv), but that's another discussion.

Removing .ruby-version might help, dunno. 

Sorry to bring more things to this PR thread but they were IMO.

**Comment by PragTob** [comment]
:+1: remove .ruby-version and PR looks good :)

**Comment by asterite** [comment]
@jhass Please merge if you think this is OK. The `.ruby-version` file doesn't bother, or can be removed if you want.

**Comment by jhass** [comment]
Well, I proposed it, of course I think it looks okay ;)

**Pull request merged**
